CREATE TABLE Parent (
  ParentID INT64 NOT NULL,
  Value STRING(100)
) PRIMARY KEY (ParentID);

CREATE TABLE Child1 (
  ParentID INT64 NOT NULL,
  Child1ID INT64 NOT NULL,
  Value STRING(100)
) PRIMARY KEY (ParentID, Child1ID),
  INTERLEAVE IN PARENT Parent ON DELETE CASCADE;

CREATE TABLE Child2 (
  ParentID INT64 NOT NULL,
  Child1ID INT64 NOT NULL,
  Child2ID INT64 NOT NULL,
  Value STRING(100)
) PRIMARY KEY (ParentID, Child1ID, Child2ID),
  INTERLEAVE IN PARENT Child1 ON DELETE CASCADE;

CREATE TABLE Child3 (
  ParentID INT64 NOT NULL,
  Child1ID INT64 NOT NULL,
  Child2ID INT64 NOT NULL,
  Child3ID INT64 NOT NULL,
  Value STRING(100)
) PRIMARY KEY (ParentID, Child1ID, Child2ID, Child3ID),
  INTERLEAVE IN PARENT Child2 ON DELETE CASCADE;

CREATE TABLE Child4 (
  ParentID INT64 NOT NULL,
  Child1ID INT64 NOT NULL,
  Child2ID INT64 NOT NULL,
  Child3ID INT64 NOT NULL,
  Child4ID INT64 NOT NULL,
  Value STRING(100)
) PRIMARY KEY (ParentID, Child1ID, Child2ID, Child3ID, Child4ID),
  INTERLEAVE IN PARENT Child3 ON DELETE CASCADE;

CREATE TABLE Child5 (
  ParentID INT64 NOT NULL,
  Child1ID INT64 NOT NULL,
  Child2ID INT64 NOT NULL,
  Child3ID INT64 NOT NULL,
  Child4ID INT64 NOT NULL,
  Child5ID INT64 NOT NULL,
  Value STRING(100)
) PRIMARY KEY (ParentID, Child1ID, Child2ID, Child3ID, Child4ID, Child5ID),
  INTERLEAVE IN PARENT Child4 ON DELETE CASCADE;

CREATE TABLE Child6 (
  ParentID INT64 NOT NULL,
  Child1ID INT64 NOT NULL,
  Child2ID INT64 NOT NULL,
  Child3ID INT64 NOT NULL,
  Child4ID INT64 NOT NULL,
  Child5ID INT64 NOT NULL,
  Child6ID INT64 NOT NULL,
  Value STRING(100)
) PRIMARY KEY (ParentID, Child1ID, Child2ID, Child3ID, Child4ID, Child5ID, Child6ID),
  INTERLEAVE IN PARENT Child5 ON DELETE CASCADE;

CREATE TABLE Child7 (
  ParentID INT64 NOT NULL,
  Child1ID INT64 NOT NULL,
  Child2ID INT64 NOT NULL,
  Child3ID INT64 NOT NULL,
  Child4ID INT64 NOT NULL,
  Child5ID INT64 NOT NULL,
  Child6ID INT64 NOT NULL,
  Child7ID INT64 NOT NULL,
  Value STRING(100)
) PRIMARY KEY (ParentID, Child1ID, Child2ID, Child3ID, Child4ID, Child5ID, Child6ID, Child7ID),
  INTERLEAVE IN PARENT Child6 ON DELETE CASCADE;
