

# Autogenerated file. DO NOT EDIT.
#
# Copyright (C) 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
#


variable "on_delete" {
  type        = string
  description = "One of \"drain\" or \"cancel\". Specifies behavior of deletion during terraform destroy."
}

variable "project" {
  type        = string
  description = "The Google Cloud Project ID within which this module provisions resources."
}

variable "region" {
  type        = string
  description = "The region in which the created job should run."
}

variable "changeStreamName" {
  type = string
  description = "This is the name of the Spanner change stream that the pipeline will read from."
  
}

variable "instanceId" {
  type = string
  description = "This is the name of the Cloud Spanner instance where the changestream is present."
  
}

variable "databaseId" {
  type = string
  description = "This is the name of the Cloud Spanner database that the changestream is monitoring"
  
}

variable "spannerProjectId" {
  type = string
  description = "This is the name of the Cloud Spanner project."
  
}

variable "metadataInstance" {
  type = string
  description = "This is the instance to store the metadata used by the connector to control the consumption of the change stream API data."
  
}

variable "metadataDatabase" {
  type = string
  description = "This is the database to store the metadata used by the connector to control the consumption of the change stream API data."
  
}

variable "startTimestamp" {
  type = string
  description = "Read changes from the given timestamp. Defaults to empty."
  default = null
}

variable "endTimestamp" {
  type = string
  description = "Read changes until the given timestamp. If no timestamp provided, reads indefinitely. Defaults to empty."
  default = null
}

variable "incrementInterval" {
  type = number
  description = "The timer gets incremented by the specified time interval in seconds. By default, the next timer is set to the current real time."
  default = null
}

variable "sinkType" {
  type = string
  description = "The type of sink where the data will get written to."
  
}

variable "pubSubDataTopicId" {
  type = string
  description = "PubSub topic where records will get written to, in the format of 'projects/your-project-id/topics/your-topic-name'. Must be provided if sink is pubsub."
  default = null
}

variable "pubSubErrorTopicId" {
  type = string
  description = "PubSub topic where error records will get written to, in the format of 'projects/your-project-id/topics/your-topic-name'. Must be provided if sink is pubsub."
  default = null
}

variable "pubSubEndpoint" {
  type = string
  description = "Endpoint for pubsub. Must be provided if sink is pubsub. Defaults to empty."
  default = null
}

variable "kafkaClusterFilePath" {
  type = string
  description = "This is the path to GCS file containing Kafka cluster details. Must be provided if sink is kafka."
  default = null
}

variable "sourceShardsFilePath" {
  type = string
  description = "Path to GCS file containing connection profile info for source shards. Must be provided if sink is kafka."
  default = null
}

variable "sessionFilePath" {
  type = string
  description = "Session file path in Cloud Storage that contains mapping information from HarbourBridge"
  
}

variable "filtrationMode" {
  type = string
  description = "Mode of Filtration, decides how to drop certain records based on a criteria. Currently supported modes are: none (filter nothing), forward_migration (filter records written via the forward migration pipeline). Defaults to forward_migration."
  default = null
}


provider "google" {
    project = var.project
}

provider "google-beta" {
    project = var.project
}

variable "additional_experiments" {
	type = set(string)
	description = "List of experiments that should be used by the job. An example value is  'enable_stackdriver_agent_metrics'."
	default = null
}

variable "autoscaling_algorithm" {
	type = string
	description = "The algorithm to use for autoscaling"
	default = null
}

variable "enable_streaming_engine" {
	type = bool
	description = "Indicates if the job should use the streaming engine feature."
	default = null
}

variable "ip_configuration" {
	type = string
	description = "The configuration for VM IPs. Options are 'WORKER_IP_PUBLIC' or 'WORKER_IP_PRIVATE'."
	default = null
}

variable "kms_key_name" {
	type = string
	description = "The name for the Cloud KMS key for the job. Key format is: projects/PROJECT_ID/locations/LOCATION/keyRings/KEY_RING/cryptoKeys/KEY"
	default = null
}

variable "labels" {
	type = map(string)
	description = "User labels to be specified for the job. Keys and values should follow the restrictions specified in the labeling restrictions page. NOTE: This field is non-authoritative, and will only manage the labels present in your configuration.				Please refer to the field 'effective_labels' for all of the labels present on the resource."
	default = null
}

variable "launcher_machine_type" {
	type = string
	description = "The machine type to use for launching the job. The default is n1-standard-1."
	default = null
}

variable "machine_type" {
	type = string
	description = "The machine type to use for the job."
	default = null
}

variable "max_workers" {
	type = number
	description = "The maximum number of Google Compute Engine instances to be made available to your pipeline during execution, from 1 to 1000."
	default = null
}

variable "name" {
	type = string
}

variable "network" {
	type = string
	description = "The network to which VMs will be assigned. If it is not provided, 'default' will be used."
	default = null
}

variable "num_workers" {
	type = number
	description = "The initial number of Google Compute Engine instances for the job."
	default = null
}

variable "sdk_container_image" {
	type = string
	description = "Docker registry location of container image to use for the 'worker harness. Default is the container for the version of the SDK. Note this field is only valid for portable pipelines."
	default = null
}

variable "service_account_email" {
	type = string
	description = "The Service Account email used to create the job."
	default = null
}

variable "skip_wait_on_job_termination" {
	type = bool
	description = "If true, treat DRAINING and CANCELLING as terminal job states and do not wait for further changes before removing from terraform state and moving on. WARNING: this will lead to job name conflicts if you do not ensure that the job names are different, e.g. by embedding a release ID or by using a random_id."
	default = null
}

variable "staging_location" {
	type = string
	description = "The Cloud Storage path to use for staging files. Must be a valid Cloud Storage URL, beginning with gs://."
	default = null
}

variable "subnetwork" {
	type = string
	description = "The subnetwork to which VMs will be assigned. Should be of the form 'regions/REGION/subnetworks/SUBNETWORK'."
	default = null
}

variable "temp_location" {
	type = string
	description = "The Cloud Storage path to use for temporary files. Must be a valid Cloud Storage URL, beginning with gs://."
	default = null
}

resource "google_project_service" "required" {
    service = "dataflow.googleapis.com"
    disable_on_destroy = false
}

resource "google_dataflow_flex_template_job" "generated" {
    depends_on = [google_project_service.required]
    provider = google-beta
    container_spec_gcs_path = "gs://dataflow-templates-${var.region}/latest/flex/Spanner_Change_Streams_to_Sink"
    parameters = {
        changeStreamName = var.changeStreamName
        instanceId = var.instanceId
        databaseId = var.databaseId
        spannerProjectId = var.spannerProjectId
        metadataInstance = var.metadataInstance
        metadataDatabase = var.metadataDatabase
        startTimestamp = var.startTimestamp
        endTimestamp = var.endTimestamp
        incrementInterval = tostring(var.incrementInterval)
        sinkType = var.sinkType
        pubSubDataTopicId = var.pubSubDataTopicId
        pubSubErrorTopicId = var.pubSubErrorTopicId
        pubSubEndpoint = var.pubSubEndpoint
        kafkaClusterFilePath = var.kafkaClusterFilePath
        sourceShardsFilePath = var.sourceShardsFilePath
        sessionFilePath = var.sessionFilePath
        filtrationMode = var.filtrationMode
    }
    
	additional_experiments = var.additional_experiments
	autoscaling_algorithm = var.autoscaling_algorithm
	enable_streaming_engine = var.enable_streaming_engine
	ip_configuration = var.ip_configuration
	kms_key_name = var.kms_key_name
	labels = var.labels
	launcher_machine_type = var.launcher_machine_type
	machine_type = var.machine_type
	max_workers = var.max_workers
	name = var.name
	network = var.network
	num_workers = var.num_workers
	sdk_container_image = var.sdk_container_image
	service_account_email = var.service_account_email
	skip_wait_on_job_termination = var.skip_wait_on_job_termination
	staging_location = var.staging_location
	subnetwork = var.subnetwork
	temp_location = var.temp_location
    region = var.region
}

output "dataflow_job_url" {
    value = "https://console.cloud.google.com/dataflow/jobs/${var.region}/${google_dataflow_flex_template_job.generated.job_id}"
}

