CREATE TABLE t_bigint (id serial primary key, col bigint);
CREATE TABLE t_bigserial (id serial primary key, col bigserial);
CREATE TABLE t_bit (id serial primary key, col bit);
CREATE TABLE t_bit_varying (id serial primary key, col bit varying);
CREATE TABLE t_bool (id serial primary key, col bool);
CREATE TABLE t_boolean (id serial primary key, col boolean);
CREATE TABLE t_box (id serial primary key, col box);
CREATE TABLE t_bytea (id serial primary key, col bytea);
CREATE TABLE t_char (id serial primary key, col char);
CREATE TABLE t_character (id serial primary key, col character);
CREATE TABLE t_character_varying (id serial primary key, col character varying);
CREATE TABLE t_cidr (id serial primary key, col cidr);
CREATE TABLE t_circle (id serial primary key, col circle);
CREATE TABLE t_date (id serial primary key, col date);
CREATE TABLE t_decimal (id serial primary key, col numeric(10,2));
CREATE TABLE t_double_precision (id serial primary key, col double precision);
CREATE TABLE t_float4 (id serial primary key, col float4);
CREATE TABLE t_float8 (id serial primary key, col float8);
CREATE TABLE t_inet (id serial primary key, col inet);
CREATE TABLE t_int (id serial primary key, col int);
CREATE TABLE t_integer (id serial primary key, col integer);
CREATE TABLE t_int2 (id serial primary key, col int2);
CREATE TABLE t_int4 (id serial primary key, col int4);
CREATE TABLE t_int8 (id serial primary key, col int8);
CREATE TABLE t_json (id serial primary key, col json);
CREATE TABLE t_jsonb (id serial primary key, col jsonb);
CREATE TABLE t_line (id serial primary key, col line);
CREATE TABLE t_lseg (id serial primary key, col lseg);
CREATE TABLE t_macaddr (id serial primary key, col macaddr);
CREATE TABLE t_macaddr8 (id serial primary key, col macaddr8);
CREATE TABLE t_money (id serial primary key, col money);
CREATE TABLE t_numeric (id serial primary key, col numeric(10,2));
CREATE TABLE t_oid (id serial primary key, col oid);
CREATE TABLE t_path (id serial primary key, col path);
CREATE TABLE t_pg_lsn (id serial primary key, col pg_lsn);
CREATE TABLE t_pg_snapshot (id serial primary key, col pg_snapshot);
CREATE TABLE t_point (id serial primary key, col point);
CREATE TABLE t_polygon (id serial primary key, col polygon);
CREATE TABLE t_real (id serial primary key, col real);
CREATE TABLE t_serial (id serial primary key, col serial);
CREATE TABLE t_serial2 (id serial primary key, col serial2);
CREATE TABLE t_serial4 (id serial primary key, col serial4);
CREATE TABLE t_serial8 (id serial primary key, col serial8);
CREATE TABLE t_smallint (id serial primary key, col smallint);
CREATE TABLE t_smallserial (id serial primary key, col smallserial);
CREATE TABLE t_text (id serial primary key, col text);
CREATE TABLE t_time (id serial primary key, col time);
CREATE TABLE t_timestamp (id serial primary key, col timestamp);
CREATE TABLE t_timestamptz (id serial primary key, col timestamptz);
CREATE TABLE t_time_without_time_zone (id serial primary key, col time without time zone);
CREATE TABLE t_timestamp_with_time_zone (id serial primary key, col timestamp with time zone);
CREATE TABLE t_timestamp_without_time_zone (id serial primary key, col timestamp without time zone);
CREATE TABLE t_tsquery (id serial primary key, col tsquery);
CREATE TABLE t_tsvector (id serial primary key, col tsvector);
CREATE TABLE t_txid_snapshot (id serial primary key, col txid_snapshot);
CREATE TABLE t_uuid (id serial primary key, col uuid);
CREATE TABLE t_varbit (id serial primary key, col varbit);
CREATE TABLE t_varchar (id serial primary key, col varchar);
CREATE TABLE t_xml (id serial primary key, col xml);

INSERT INTO t_bigint (col) VALUES (-9223372036854775808), (9223372036854775807), (42), (NULL);
INSERT INTO t_bigserial (col) VALUES (-9223372036854775808), (9223372036854775807), (42);
INSERT INTO t_bit (col) VALUES (0::bit), (1::bit), (NULL);
INSERT INTO t_bit_varying (col) VALUES ('0101'::bit varying), (NULL);
INSERT INTO t_bool (col) VALUES (false), (true), (NULL);
INSERT INTO t_boolean (col) VALUES (false), (true), (NULL);
INSERT INTO t_box (col) VALUES ('((1, 2), (3, 4))'), (NULL);
INSERT INTO t_bytea (col) VALUES ('abc'::bytea), (NULL);
INSERT INTO t_char (col) VALUES ('a'), ('Θ'), (NULL);
INSERT INTO t_character (col) VALUES ('a'), ('Ξ'), (NULL);
INSERT INTO t_character_varying (col) VALUES ('testing character varying'), (NULL);
INSERT INTO t_cidr (col) VALUES ('192.168.100.128/25'), ('192.168.1'), ('192'), ('::ffff:1.2.3.0/128'), (NULL);
INSERT INTO t_circle (col) VALUES ('((1, 2), 3)'), (NULL);
INSERT INTO t_date (col) VALUES ('0001-01-01'::date), ('9999-12-31'::date), (NULL);
INSERT INTO t_decimal (col) VALUES (0.12), (NULL);
INSERT INTO t_double_precision (col) VALUES ('-1.9876542e307'), ('1.9876542e307'), ('NaN'), ('-Infinity'), ('Infinity'), (1.23), (NULL);
INSERT INTO t_float4 (col) VALUES ('-1.9876542e38'), ('1.9876542e38'), ('NaN'), ('-Infinity'), ('Infinity'), (2.34), (NULL);
INSERT INTO t_float8 (col) VALUES ('-1.9876542e307'), ('1.9876542e307'), ('NaN'), ('-Infinity'), ('Infinity'), (3.45), (NULL);
INSERT INTO t_inet (col) VALUES ('192.168.1.0/24'), (NULL);
INSERT INTO t_int (col) VALUES (-2147483648), (2147483647), (1), (NULL);
INSERT INTO t_integer (col) VALUES (-2147483648), (2147483647), (2), (NULL);
INSERT INTO t_int2 (col) VALUES (-32768), (32767), (3), (NULL);
INSERT INTO t_int4 (col) VALUES (-2147483648), (2147483647), (4), (NULL);
INSERT INTO t_int8 (col) VALUES (-9223372036854775808), (9223372036854775807), (5), (NULL);
INSERT INTO t_json (col) VALUES ('{"duplicate_key": 1, "duplicate_key": 2}'), ('{"null_key": null}'), (NULL);
INSERT INTO t_jsonb (col) VALUES ('{"duplicate_key": 1, "duplicate_key": 2}'), ('{"null_key": null}'), (NULL);
INSERT INTO t_line (col) VALUES ('{ 1, 2, 3 }'), (NULL);
INSERT INTO t_lseg (col) VALUES ('[ (1, 2), (3, 4) ]'), (NULL);
INSERT INTO t_macaddr (col) VALUES ('08:00:2b:01:02:03'), (NULL);
INSERT INTO t_macaddr8 (col) VALUES ('08:00:2b:01:02:03:04:05'), (NULL);
INSERT INTO t_money (col) VALUES ('123.45'::money), (NULL);
INSERT INTO t_numeric (col) VALUES (4.56), (NULL);
INSERT INTO t_oid (col) VALUES (1000::oid), (NULL);
INSERT INTO t_path (col) VALUES ('[ (1, 2), (3, 4), (5, 6) ]'), (NULL);
INSERT INTO t_pg_lsn (col) VALUES ('123/0'::pg_lsn), (NULL);
INSERT INTO t_pg_snapshot (col) VALUES ('1000:1000:'::pg_snapshot), (NULL);
INSERT INTO t_point (col) VALUES ('(1, 2)'), (NULL);
INSERT INTO t_polygon (col) VALUES ('( (1, 2), (3, 4) )'), (NULL);
INSERT INTO t_real (col) VALUES ('-1.9876542e38'), ('1.9876542e38'), ('NaN'), ('-Infinity'), ('Infinity'), (5.67), (NULL);
INSERT INTO t_serial (col) VALUES (-2147483648), (2147483647), (6);
INSERT INTO t_serial2 (col) VALUES (-32768), (32767), (7);
INSERT INTO t_serial4 (col) VALUES (-2147483648), (2147483647), (8);
INSERT INTO t_serial8 (col) VALUES (-9223372036854775808), (9223372036854775807), (9);
INSERT INTO t_smallint (col) VALUES (-32768), (32767), (10), (NULL);
INSERT INTO t_smallserial (col) VALUES (-32768), (32767), (11);
INSERT INTO t_text (col) VALUES ('testing text'), (NULL);
INSERT INTO t_time (col) VALUES ('00:00:00'::time), ('23:59:59'::time), ('24:00:00'::time), (NULL);
INSERT INTO t_timestamp (col) VALUES ('1970-01-02 03:04:05.123456'::timestamp), (NULL);
INSERT INTO t_timestamptz (col) VALUES ('1970-02-03 04:05:06.123456+10:00'::timestamptz), ('1970-02-03 04:05:06.123456-01'::timestamptz), (NULL);
INSERT INTO t_time_without_time_zone (col) VALUES ('00:00:00'::time), ('23:59:59'::time), ('24:00:00'::time), (NULL);
INSERT INTO t_timestamp_with_time_zone (col) VALUES ('1970-02-03 04:05:06.123456+10:00'::timestamptz), ('1970-02-03 04:05:06.123456-01'::timestamptz), (NULL);
INSERT INTO t_timestamp_without_time_zone (col) VALUES ('1970-01-02 03:04:05.123456'::timestamp), (NULL);
INSERT INTO t_tsquery (col) VALUES ('fat & rat'::tsquery), (NULL);
INSERT INTO t_tsvector (col) VALUES ('a fat cat sat on a mat'::tsvector), (NULL);
INSERT INTO t_txid_snapshot (col) VALUES ('10:20:10,14,15'::txid_snapshot), (NULL);
INSERT INTO t_uuid (col) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'::uuid), (NULL);
INSERT INTO t_varbit (col) VALUES ('1100'::varbit), (NULL);
INSERT INTO t_varchar (col) VALUES ('testing varchar'), (NULL);
INSERT INTO t_xml (col) VALUES ('<test>123</test>'::xml), (NULL);
