#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Mar 27 14:00:29 EDT 2026
maven-metadata-confluent.xml.error=
maven-metadata-confluent.xml.lastUpdated=1774634429454
maven-metadata-splunk-artifactory.xml.error=
maven-metadata-splunk-artifactory.xml.lastUpdated=1774634429456
