CREATE TABLE person (
     first_name1 BYTES(MAX),
     last_name1 BYTES(MAX),
     first_name2 BYTES(MAX),
     last_name2 BYTES(MAX),
     first_name3 BYTES(MAX),
     last_name3 BYTES(MAX),
     first_name4 BYTES(MAX),
     last_name4 BYTES(MAX),
     first_name5 BYTES(MAX),
     last_name5 BYTES(MAX),
     first_name6 BYTES(MAX),
     last_name6 BYTES(MAX),
     first_name7 BYTES(MAX),
     last_name7 BYTES(MAX),
     first_name8 BYTES(MAX),
     last_name8 BYTES(MAX),
     first_name9 BYTES(MAX),
     last_name9 BYTES(MAX),
     first_name10 BYTES(MAX),
     last_name10 BYTES(MAX),
     ID INT64 NOT NULL,
) PRIMARY KEY(ID);