CREATE TABLE t10 (
    id INT64 NOT NULL
) PRIMARY KEY(id);

CREATE TABLE t9 (
    id INT64 NOT NULL,
    CONSTRAINT fk_t9_t10 FOREIGN KEY(id) REFERENCES t10(id)
) PRIMARY KEY(id);

CREATE TABLE t8 (
    id INT64 NOT NULL,
    CONSTRAINT fk_t8_t9 FOREIGN KEY(id) REFERENCES t9(id)
) PRIMARY KEY(id);

CREATE TABLE t7 (
    id INT64 NOT NULL,
    CONSTRAINT fk_t7_t8 FOREIGN KEY(id) REFERENCES t8(id)
) PRIMARY KEY(id);

CREATE TABLE t6 (
    id INT64 NOT NULL,
    CONSTRAINT fk_t6_t7 FOREIGN KEY(id) REFERENCES t7(id)
) PRIMARY KEY(id);

CREATE TABLE t5 (
    id INT64 NOT NULL,
    CONSTRAINT fk_t5_t6 FOREIGN KEY(id) REFERENCES t6(id)
) PRIMARY KEY(id);

CREATE TABLE t4 (
    id INT64 NOT NULL,
    CONSTRAINT fk_t4_t5 FOREIGN KEY(id) REFERENCES t5(id)
) PRIMARY KEY(id);

CREATE TABLE t3 (
    id INT64 NOT NULL,
    CONSTRAINT fk_t3_t4 FOREIGN KEY(id) REFERENCES t4(id)
) PRIMARY KEY(id);

CREATE TABLE t2 (
    id INT64 NOT NULL,
    CONSTRAINT fk_t2_t3 FOREIGN KEY(id) REFERENCES t3(id)
) PRIMARY KEY(id);

CREATE TABLE t1 (
    id INT64 NOT NULL,
) PRIMARY KEY(id),
  INTERLEAVE IN PARENT t2 ON DELETE CASCADE;