comment:
  layout: "header, diff, components, files" # show component info in the PR comment

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        target: 80%
        informational: true

component_management:
  individual_components:
  - component_id: spanner-templates
    name: spanner-templates
    paths:
    - "v1/src/main/java/com/google/cloud/teleport/spanner/**"
    - "v1/src/main/java/com/google/cloud/teleport/templates/SpannerToText.java"
    - "v1/src/main/java/com/google/cloud/teleport/templates/common/SpannerConverters.java"
    - "v2/datastream-to-spanner/**"
    - "v2/spanner-common/**"
    - "v2/spanner-change-streams-to-sharded-file-sink/**"
    - "v2/gcs-to-sourcedb/**"
    - "v2/spanner-migrations-sdk/**"
    - "v2/spanner-custom-shard/**"
    - "v2/sourcedb-to-spanner/**"
    statuses:
    - type: project
      informational: true
    - type: patch
      target: 80%
  - component_id: spanner-import-export
    name: spanner-import-export
    paths:
    - "v1/src/main/java/com/google/cloud/teleport/spanner/**"
    - "v1/src/main/java/com/google/cloud/teleport/templates/SpannerToText.java"
    - "v1/src/main/java/com/google/cloud/teleport/templates/common/SpannerConverters.java"
  - component_id: spanner-live-forward-migration
    name: spanner-live-forward-migration
    paths:
    - "v2/datastream-to-spanner/**"
    - "v2/spanner-common/**"
  - component_id: spanner-live-reverse-replication
    name: spanner-live-reverse-replication
    paths:
    - "v2/spanner-change-streams-to-sharded-file-sink/**"
    - "v2/gcs-to-sourcedb/**"
    - "v2/spanner-migrations-sdk/**"
    - "v2/spanner-custom-shard/**"
    - "v2/spanner-common/**"
  - component_id: spanner-bulk-migration
    name: spanner-bulk-migration
    paths:
    - "v2/sourcedb-to-spanner/**"
    - "v2/spanner-common/**"
    - "!v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/constants/**"
