comment:
  layout: "header, diff, components, files" # show component info in the PR comment

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        target: 80%
        informational: true

component_management:
  individual_components:
  - component_id: spanner-templates
    name: spanner-templates
    paths:
    - "v2/datastream-to-spanner/**"
    - "v2/spanner-common/**"
    - "v2/spanner-migrations-sdk/**"
    - "v2/spanner-custom-shard/**"
    - "v2/sourcedb-to-spanner/**"
    - "v2/spanner-to-sourcedb/**"
    - "v2/gcs-spanner-dv/**"
    statuses:
    - type: project
      target: 80%
    - type: patch
      target: 80%
  - component_id: spanner-import-export
    name: spanner-import-export
    paths:
    - "v1/src/main/java/com/google/cloud/teleport/spanner/**"
    - "v1/src/main/java/com/google/cloud/teleport/templates/SpannerToText.java"
    - "v1/src/main/java/com/google/cloud/teleport/templates/common/SpannerConverters.java"
  - component_id: spanner-live-forward-migration
    name: spanner-live-forward-migration
    paths:
    - "v2/datastream-to-spanner/**"
    - "v2/spanner-common/**"
    - "v2/spanner-migrations-sdk/**"
  - component_id: spanner-live-reverse-replication
    name: spanner-live-reverse-replication
    paths:
    - "v2/spanner-to-sourcedb/**"
    - "v2/spanner-migrations-sdk/**"
    - "v2/spanner-custom-shard/**"
    - "v2/spanner-common/**"
  - component_id: spanner-bulk-migration
    name: spanner-bulk-migration
    paths:
    - "v2/sourcedb-to-spanner/**"
    - "v2/spanner-common/**"
    - "!v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/constants/**"
  - component_id: gcs-spanner-dv
    name: gcs-spanner-dv
    paths:
    - "v2/gcs-spanner-dv/**"
    - "v2/spanner-common/**"

# Flags are used to identify reports from different workflows.
# In a monorepo with path-based triggers (like this one), not all workflows run on every commit.
# Enabling 'carryforward' allows Codecov to use the coverage report from a previous commit
# for workflows that were skipped in the current commit, preventing status checks from hanging
# and providing a complete picture of the codebase coverage.
flags:
  spanner:
    carryforward: true
  java:
    carryforward: true
