version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /cicd
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    exclude-paths:
      - "python/src/main/python/**/requirements.txt"
      - "yaml/src/main/python/requirements.txt"
      - "v2/**/resources/requirements.txt"
      - "yaml/src/main/java/com/google/cloud/teleport/templates/yaml/requirements.txt"

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
