changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New Templates
      labels:
        - new-templates
    - title: Improvements
      labels:
        - improvement
    - title: Bug fixes
      labels:
        - bug-fixes
