CREATE TABLE OracleAllDatatypes (
  id INT64 NOT NULL,
  varchar2_col STRING(MAX),
  varchar_col STRING(MAX),
  char_col STRING(MAX),
  character_col STRING(MAX),
  nvarchar2_col STRING(MAX),
  nchar_col STRING(MAX),
  number_col NUMERIC,
  numeric_col NUMERIC,
  decimal_col NUMERIC,
  dec_col NUMERIC,
  float_col FLOAT64,
  double_precision_col FLOAT64,
  real_col FLOAT64,
  binary_float_col FLOAT32,
  binary_double_col FLOAT64,
  integer_col INT64,
  int_col INT64,
  smallint_col INT64,
  date_col TIMESTAMP,
  timestamp_col TIMESTAMP,
  timestamp_tz_col TIMESTAMP,
  timestamp_ltz_col TIMESTAMP,
  interval_ym_col STRING(MAX),
  interval_ds_col STRING(MAX),
  raw_col BYTES(MAX),
  blob_col BYTES(MAX),
  clob_col STRING(MAX),
  nclob_col STRING(MAX),
  rowid_col STRING(MAX),
  json_col JSON,
  xmltype_col STRING(MAX)
) PRIMARY KEY(id);
