FROM ${baseContainerImage}

ARG WORKDIR=/template
RUN mkdir -p $WORKDIR
COPY ${containerName}/main.py $WORKDIR
COPY ${containerName}/requirements.txt $WORKDIR
WORKDIR $WORKDIR

ENV FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE=requirements.txt
ENV FLEX_TEMPLATE_PYTHON_PY_FILE=main.py

RUN pip install 'apache-beam[gcp]'
RUN pip install -U -r $FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE
RUN pip download --no-cache-dir --dest /tmp/dataflow-requirements-cache -r $FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE

ENTRYPOINT ["/opt/google/dataflow/python_template_launcher"]