/* GENERATED BY: Test Automation Skill */
/*
 * Copyright (C) 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.google.cloud.teleport.v2.templates.oracle;

import static org.apache.beam.it.truthmatchers.PipelineAsserts.assertThatResult;

import com.google.cloud.Timestamp;
import com.google.cloud.spanner.Struct;
import com.google.cloud.teleport.metadata.SkipDirectRunnerTest;
import com.google.cloud.teleport.metadata.TemplateIntegrationTest;
import com.google.cloud.teleport.v2.templates.DataStreamToSpanner;
import com.google.cloud.teleport.v2.templates.DataStreamToSpannerITBase;
import com.google.common.collect.ImmutableList;
import java.io.IOException;
import java.time.Duration;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import org.apache.beam.it.common.PipelineLauncher;
import org.apache.beam.it.common.PipelineOperator;
import org.apache.beam.it.common.utils.ResourceManagerUtils;
import org.apache.beam.it.conditions.ChainedConditionCheck;
import org.apache.beam.it.gcp.pubsub.PubsubResourceManager;
import org.apache.beam.it.gcp.spanner.SpannerResourceManager;
import org.apache.beam.it.gcp.spanner.conditions.SpannerRowsCheck;
import org.apache.beam.it.gcp.spanner.matchers.SpannerAsserts;
import org.apache.beam.it.gcp.storage.GcsResourceManager;
import org.junit.AfterClass;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@Category({TemplateIntegrationTest.class, SkipDirectRunnerTest.class})
@TemplateIntegrationTest(DataStreamToSpanner.class)
@RunWith(JUnit4.class)
public class OracleDataStreamToSpannerEventsIT extends DataStreamToSpannerITBase {

  private static final Logger LOG = LoggerFactory.getLogger(OracleDataStreamToSpannerEventsIT.class);

  private static final String TABLE1 = "Users";
  private static final String TABLE2 = "Movie";

  private static final String SPANNER_DDL_RESOURCE =
      "oracle/OracleDataStreamToSpannerEventsIT/oracle-google_standard_sql-spanner-schema.sql";

  private static HashSet<OracleDataStreamToSpannerEventsIT> testInstances = new HashSet<>();
  private static PipelineLauncher.LaunchInfo jobInfo;

  public static PubsubResourceManager pubsubResourceManager;
  public static SpannerResourceManager spannerResourceManager;
  public static GcsResourceManager gcsResourceManager;

  @Before
  public void setUp() throws IOException {
    skipBaseCleanup = true;
    synchronized (OracleDataStreamToSpannerEventsIT.class) {
      testInstances.add(this);
      if (jobInfo == null) {
        spannerResourceManager = setUpSpannerResourceManager();
        pubsubResourceManager = setUpPubSubResourceManager();
        gcsResourceManager = setUpSpannerITGcsResourceManager();
        createSpannerDDL(spannerResourceManager, SPANNER_DDL_RESOURCE);
        jobInfo =
            launchDataflowJob(
                getClass().getSimpleName(),
                null,
                null,
                "OracleEventsIT",
                spannerResourceManager,
                pubsubResourceManager,
                new HashMap<>() {
                  {
                    put("inputFileFormat", "avro");
                    put("datastreamSourceType", "oracle");
                  }
                },
                null,
                null,
                gcsResourceManager);
      }
    }
  }

  @AfterClass
  public static void cleanUp() throws IOException {
    for (OracleDataStreamToSpannerEventsIT instance : testInstances) {
      instance.tearDownBase();
    }
    ResourceManagerUtils.cleanResources(
        spannerResourceManager, pubsubResourceManager, gcsResourceManager);
  }

  @Test
  public void migrationTestWithUpdatesAndDeletes() {
    ChainedConditionCheck conditionCheck =
        ChainedConditionCheck.builder(
                List.of(
                    uploadDataStreamFile(
                        jobInfo,
                        TABLE1,
                        "backfill_users.avro",
                        "oracle/OracleDataStreamToSpannerEventsIT/oracle-backfill-Users.avro",
                        gcsResourceManager),
                    SpannerRowsCheck.builder(spannerResourceManager, TABLE1)
                        .setMinRows(2)
                        .setMaxRows(2)
                        .build(),
                    uploadDataStreamFile(
                        jobInfo,
                        TABLE1,
                        "cdc_users.avro",
                        "oracle/OracleDataStreamToSpannerEventsIT/oracle-cdc-Users.avro",
                        gcsResourceManager),
                    SpannerRowsCheck.builder(spannerResourceManager, TABLE1)
                        .setMinRows(3)
                        .setMaxRows(3)
                        .build()))
            .build();

    PipelineOperator.Result result =
        pipelineOperator()
            .waitForCondition(
                createConfig(jobInfo, Duration.ofMinutes(JOB_START_PROCESSING_WAIT_MINUTES)),
                conditionCheck);

    assertThatResult(result).meetsConditions();

    try {
      Thread.sleep(CUTOVER_MILLIS);
    } catch (InterruptedException e) {
    }
    assertUsersTableContents();
  }

  @Test
  public void migrationTestWithInsertsOnly() {
    ChainedConditionCheck conditionCheck =
        ChainedConditionCheck.builder(
                List.of(
                    uploadDataStreamFile(
                        jobInfo,
                        TABLE2,
                        "backfill_movie.avro",
                        "oracle/OracleDataStreamToSpannerEventsIT/oracle-backfill-Movie.avro",
                        gcsResourceManager),
                    SpannerRowsCheck.builder(spannerResourceManager, TABLE2)
                        .setMinRows(2)
                        .setMaxRows(2)
                        .build()))
            .build();

    PipelineOperator.Result result =
        pipelineOperator()
            .waitForCondition(
                createConfig(jobInfo, Duration.ofMinutes(JOB_START_PROCESSING_WAIT_MINUTES)),
                conditionCheck);

    assertThatResult(result).meetsConditions();

    assertMovieTableContents();
  }

  @Test
  public void interleavedAndFKAndIndexTest() {
    ChainedConditionCheck conditionCheck =
        ChainedConditionCheck.builder(
                List.of(
                    uploadDataStreamFile(
                        jobInfo,
                        "Articles",
                        "mysql_articles.avro",
                        "oracle/OracleDataStreamToSpannerEventsIT/oracle-Articles.avro",
                        gcsResourceManager),
                    uploadDataStreamFile(
                        jobInfo,
                        "Authors",
                        "mysql_authors.avro",
                        "oracle/OracleDataStreamToSpannerEventsIT/oracle-Authors.avro",
                        gcsResourceManager),
                    uploadDataStreamFile(
                        jobInfo,
                        "Books",
                        "mysql_books.avro",
                        "oracle/OracleDataStreamToSpannerEventsIT/oracle-Books.avro",
                        gcsResourceManager),
                    SpannerRowsCheck.builder(spannerResourceManager, "Articles")
                        .setMinRows(4)
                        .setMaxRows(4)
                        .build(),
                    SpannerRowsCheck.builder(spannerResourceManager, "Books")
                        .setMinRows(4)
                        .setMaxRows(4)
                        .build(),
                    SpannerRowsCheck.builder(spannerResourceManager, "Authors")
                        .setMinRows(4)
                        .setMaxRows(4)
                        .build()))
            .build();

    PipelineOperator.Result result =
        pipelineOperator()
            .waitForCondition(createConfig(jobInfo, Duration.ofMinutes(18)), conditionCheck);

    assertThatResult(result).meetsConditions();

    assertAuthorsTable();
    assertBooksTable();
    assertArticlesTable();
  }

  private void assertUsersTableContents() {
    List<Map<String, Object>> events = new ArrayList<>();

    Map<String, Object> row1 = new HashMap<>();
    row1.put("id", 1);
    row1.put("name", "Tester Kumar");
    row1.put("age", 30);
    row1.put("subscribed", false);
    row1.put("plan", "A");
    row1.put("startDate", Timestamp.parseTimestamp("2023-01-01T00:00:00Z"));

    Map<String, Object> row2 = new HashMap<>();
    row2.put("id", 3);
    row2.put("name", "Tester Gupta");
    row2.put("age", 50);
    row2.put("subscribed", false);
    row2.put("plan", "Z");
    row2.put("startDate", Timestamp.parseTimestamp("2023-06-07T00:00:00Z"));

    Map<String, Object> row3 = new HashMap<>();
    row3.put("id", 4);
    row3.put("name", "Tester");
    row3.put("age", 38);
    row3.put("subscribed", true);
    row3.put("plan", "D");
    row3.put("startDate", Timestamp.parseTimestamp("2023-09-10T00:00:00Z"));
    events.add(row1);
    events.add(row2);
    events.add(row3);

    SpannerAsserts.assertThatStructs(
            spannerResourceManager.runQuery("select * from Users where id in (1, 3, 4)"))
        .hasRecordsUnorderedCaseInsensitiveColumns(events);
  }

  private void assertMovieTableContents() {
    List<Map<String, Object>> events = new ArrayList<>();

    Map<String, Object> row1 = new HashMap<>();
    row1.put("id", 1);
    row1.put("name", "movie1");
    row1.put("startTime", Timestamp.parseTimestamp("2023-01-01T12:12:12.000Z"));

    Map<String, Object> row2 = new HashMap<>();
    row2.put("id", 2);
    row2.put("name", "movie2");
    row2.put("startTime", Timestamp.parseTimestamp("2023-11-25T17:10:12.000Z"));

    events.add(row1);
    events.add(row2);

    SpannerAsserts.assertThatStructs(
            spannerResourceManager.runQuery(
                "select id, name, startTime from Movie where id in (1, 2)"))
        .hasRecordsUnorderedCaseInsensitiveColumns(events);

    ImmutableList<Struct> numericVals =
        spannerResourceManager.runQuery("select actor from Movie order by id");
    Assert.assertEquals(12345.09876, numericVals.get(0).getBigDecimal(0).doubleValue(), 0.00000001);
    Assert.assertEquals(931.5123, numericVals.get(1).getBigDecimal(0).doubleValue(), 0.00000001);
  }

  private void assertAuthorsTable() {
    List<Map<String, Object>> events = new ArrayList<>();

    Map<String, Object> row = new HashMap<>();
    row.put("author_id", 1);
    row.put("name", "a1");
    events.add(row);

    row = new HashMap<>();
    row.put("author_id", 2);
    row.put("name", "a2");
    events.add(row);

    row = new HashMap<>();
    row.put("author_id", 3);
    row.put("name", "a3");
    events.add(row);

    row = new HashMap<>();
    row.put("author_id", 4);
    row.put("name", "a4");
    events.add(row);

    SpannerAsserts.assertThatStructs(spannerResourceManager.runQuery("select * from Authors"))
        .hasRecordsUnorderedCaseInsensitiveColumns(events);
  }

  private void assertBooksTable() {
    List<Map<String, Object>> events = new ArrayList<>();

    Map<String, Object> row = new HashMap<>();
    row.put("id", 1);
    row.put("title", "Book005");
    row.put("author_id", 3);
    events.add(row);

    row = new HashMap<>();
    row.put("id", 2);
    row.put("title", "Book002");
    row.put("author_id", 3);
    events.add(row);

    row = new HashMap<>();
    row.put("id", 3);
    row.put("title", "Book004");
    row.put("author_id", 4);
    events.add(row);

    row = new HashMap<>();
    row.put("id", 4);
    row.put("title", "Book005");
    row.put("author_id", 2);
    events.add(row);

    SpannerAsserts.assertThatStructs(
            spannerResourceManager.runQuery("select * from Books@{FORCE_INDEX=author_id_6}"))
        .hasRecordsUnorderedCaseInsensitiveColumns(events);
  }

  private void assertArticlesTable() {
    List<Map<String, Object>> events = new ArrayList<>();

    Map<String, Object> row = new HashMap<>();
    row.put("id", 1);
    row.put("name", "Article001");
    row.put("published_date", Timestamp.parseTimestamp("2024-01-01T00:00:00Z"));
    row.put("author_id", 1);
    events.add(row);

    row = new HashMap<>();
    row.put("id", 2);
    row.put("name", "Article002");
    row.put("published_date", Timestamp.parseTimestamp("2024-01-01T00:00:00Z"));
    row.put("author_id", 1);
    events.add(row);

    row = new HashMap<>();
    row.put("id", 3);
    row.put("name", "Article004");
    row.put("published_date", Timestamp.parseTimestamp("2024-01-01T00:00:00Z"));
    row.put("author_id", 4);
    events.add(row);

    row = new HashMap<>();
    row.put("id", 4);
    row.put("name", "Article005");
    row.put("published_date", Timestamp.parseTimestamp("2024-01-01T00:00:00Z"));
    row.put("author_id", 3);
    events.add(row);

    SpannerAsserts.assertThatStructs(
            spannerResourceManager.runQuery("select * from Articles@{FORCE_INDEX=author_id}"))
        .hasRecordsUnorderedCaseInsensitiveColumns(events);
  }
}
