DROP TABLE IF EXISTS `%PREFIX%EmptyTable`;
CREATE TABLE `%PREFIX%EmptyTable` (
    id INT64 NOT NULL
) PRIMARY KEY(id);

ALTER DATABASE db SET OPTIONS (default_sequence_kind = 'bit_reversed_positive');

DROP TABLE IF EXISTS `%PREFIX%Identity`;
CREATE TABLE `%PREFIX%Identity` (
                               Id INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE),
                               NonKeyIdCol1 INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                               NonKeyIdCol2 INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (SKIP RANGE 1000, 2000)
) PRIMARY KEY(Id);

DROP SEQUENCE IF EXISTS `%PREFIX%Sequence1`;
CREATE SEQUENCE `%PREFIX%Sequence1` BIT_REVERSED_POSITIVE SKIP RANGE 99, 999;

DROP SEQUENCE IF EXISTS `%PREFIX%Sequence2`;
CREATE SEQUENCE `%PREFIX%Sequence2`;

DROP TABLE IF EXISTS `%PREFIX%Root`;
CREATE TABLE `%PREFIX%Root` (
    Id INT64 NOT NULL
) PRIMARY KEY(Id);

DROP TABLE IF EXISTS `%PREFIX%Singers`;
CREATE TABLE `%PREFIX%Singers` (
                              Id INT64 NOT NULL,
                              FirstName String(1024),
                              LastName String(1024),
                              Rating FLOAT32,
                              Review String(MAX),
                              `MyTokens` TOKENLIST AS (TOKENIZE_FULLTEXT(Review)) HIDDEN
) PRIMARY KEY(Id), INTERLEAVE IN `%PREFIX%Root`;

CREATE CHANGE STREAM `%PREFIX%SingersChanges` FOR `%PREFIX%Singers`;

DROP MODEL IF EXISTS `%PREFIX%ModelStruct`;
CREATE MODEL `%PREFIX%ModelStruct`
 INPUT(content STRING(MAX))
 OUTPUT (embeddings STRUCT<statistics STRUCT<truncated BOOL, token_count FLOAT64>, values ARRAY<FLOAT64>>)
 REMOTE OPTIONS (endpoint="//aiplatform.googleapis.com/projects/span-cloud-testing/locations/us-central1/publishers/google/models/textembedding-gecko");

CREATE SCHEMA `%PREFIX%UdfSchema`;

CREATE FUNCTION `%PREFIX%UdfSchema`.`Remote`(x INT64, y INT64) RETURNS INT64 NOT DETERMINISTIC LANGUAGE REMOTE OPTIONS (
  endpoint = "https://us-central1-myproject.cloudfunctions.net/myfunc",
  max_batching_rows = 10
);

DROP SEARCH INDEX IF EXISTS `%PREFIX%SequenceIndex`;
CREATE SEARCH INDEX `%PREFIX%SearchIndex`
 ON `%PREFIX%Singers`(`MyTokens`)
 OPTIONS (sort_order_sharding=TRUE);
