DROP TABLE IF EXISTS "%PREFIX%EmptyTable";
CREATE TABLE "%PREFIX%EmptyTable" (
                                 id bigint NOT NULL,
                                 PRIMARY KEY(id)
);

ALTER DATABASE db SET spanner.default_sequence_kind = 'bit_reversed_positive';

DROP TABLE IF EXISTS "%PREFIX%Identity";
CREATE TABLE "%PREFIX%Identity" (
                               Id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE) PRIMARY KEY,
                               NonKeyIdCol1 bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                               NonKeyIdCol2 bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (SKIP RANGE 1000 2000)
);

DROP SEQUENCE IF EXISTS "%PREFIX%Sequence1";
CREATE SEQUENCE "%PREFIX%Sequence1" BIT_REVERSED_POSITIVE SKIP RANGE 99 999;

DROP SEQUENCE IF EXISTS "%PREFIX%Sequence2";
CREATE SEQUENCE "%PREFIX%Sequence2";

DROP TABLE IF EXISTS "%PREFIX%Root";
CREATE TABLE "%PREFIX%Root" (
                           "Id" bigint,
                           PRIMARY KEY("Id")
);

DROP TABLE IF EXISTS "%PREFIX%Singers";
CREATE TABLE "%PREFIX%Singers" (
                              "Id" bigint,
                              "FirstName" character varying(256),
                              "LastName" character varying(256),
                              "Rating" real,
                              "NameTokens" spanner.tokenlist generated always as (spanner.tokenize_fulltext("FirstName")) stored hidden,
                              PRIMARY KEY("Id")) INTERLEAVE IN "%PREFIX%Root";

CREATE CHANGE STREAM "%PREFIX%SingersChanges" FOR "%PREFIX%Singers";

CREATE SCHEMA "%PREFIX%UdfSchema";

DROP SEARCH INDEX IF EXISTS "%PREFIX%SearchIndex";
CREATE SEARCH INDEX "%PREFIX%SearchIndex"
  ON "%PREFIX%Singers"("NameTokens") ORDER BY "Id" WHERE "Id" IS NOT NULL
  WITH (sort_order_sharding=TRUE);

DROP TABLE IF EXISTS "%PREFIX%_CustomDictionary";
CREATE TABLE "%PREFIX%_CustomDictionary" (
    "Key" character varying NOT NULL,
    "Value" character varying[] NOT NULL,
    PRIMARY KEY("Key")
) WITH (fulltext_dictionary_table=true);

