DROP TABLE IF EXISTS `%PREFIX%_EmptyTable`;
CREATE TABLE `%PREFIX%_EmptyTable` (
    id INT64 NOT NULL
) PRIMARY KEY(id);

ALTER DATABASE db SET OPTIONS (default_sequence_kind = 'bit_reversed_positive');

DROP TABLE IF EXISTS `%PREFIX%_Identity`;
CREATE TABLE `%PREFIX%_Identity` (
                               Id INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE),
                               NonKeyIdCol1 INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                               NonKeyIdCol2 INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (SKIP RANGE 1000, 2000)
) PRIMARY KEY(Id);

DROP SEQUENCE IF EXISTS `%PREFIX%_Sequence1`;
CREATE SEQUENCE `%PREFIX%_Sequence1` BIT_REVERSED_POSITIVE SKIP RANGE 99, 999;

DROP SEQUENCE IF EXISTS `%PREFIX%_Sequence2`;
CREATE SEQUENCE `%PREFIX%_Sequence2`;

DROP TABLE IF EXISTS `%PREFIX%_Root`;
CREATE TABLE `%PREFIX%_Root` (
    Id INT64 NOT NULL
) PRIMARY KEY(Id);

DROP TABLE IF EXISTS `%PREFIX%_Singers`;
CREATE TABLE `%PREFIX%_Singers` (
                              Id INT64 NOT NULL,
                              FirstName String(1024),
                              LastName String(1024),
                              Rating FLOAT32,
                              Review String(MAX),
                              `MyTokens` TOKENLIST AS (TOKENIZE_FULLTEXT(Review)) HIDDEN
) PRIMARY KEY(Id), INTERLEAVE IN `%PREFIX%_Root`;

DROP MODEL IF EXISTS `%PREFIX%_ModelStruct`;
CREATE MODEL `%PREFIX%_ModelStruct`
 INPUT(content STRING(MAX))
 OUTPUT (embeddings STRUCT<statistics STRUCT<truncated BOOL, token_count FLOAT64>, values ARRAY<FLOAT64>>)
 REMOTE OPTIONS (endpoint="//aiplatform.googleapis.com/projects/span-cloud-testing/locations/us-central1/publishers/google/models/textembedding-gecko");

DROP SEARCH INDEX IF EXISTS `%PREFIX%_SequenceIndex`;
CREATE SEARCH INDEX `%PREFIX%_SearchIndex`
 ON `%PREFIX%_Singers`(`MyTokens`)
 OPTIONS (sort_order_sharding=TRUE);
