DROP TABLE IF EXISTS "%PREFIX%_EmptyTable";
CREATE TABLE "%PREFIX%_EmptyTable" (
                                 id bigint NOT NULL,
                                 PRIMARY KEY(id)
);

ALTER DATABASE db SET spanner.default_sequence_kind = 'bit_reversed_positive';

DROP TABLE IF EXISTS "%PREFIX%_Identity";
CREATE TABLE "%PREFIX%_Identity" (
                               Id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE) PRIMARY KEY,
                               NonKeyIdCol1 bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                               NonKeyIdCol2 bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (SKIP RANGE 1000 2000)
);

DROP SEQUENCE IF EXISTS "%PREFIX%_Sequence1";
CREATE SEQUENCE "%PREFIX%_Sequence1" BIT_REVERSED_POSITIVE SKIP RANGE 99 999;

DROP SEQUENCE IF EXISTS "%PREFIX%_Sequence2";
CREATE SEQUENCE "%PREFIX%_Sequence2";

DROP TABLE IF EXISTS "%PREFIX%_Root";
CREATE TABLE "%PREFIX%_Root" (
                           "Id" bigint,
                           PRIMARY KEY("Id")
);

DROP TABLE IF EXISTS "%PREFIX%_Singers";
CREATE TABLE "%PREFIX%_Singers" (
                              "Id" bigint,
                              "FirstName" character varying(256),
                              "LastName" character varying(256),
                              "Rating" real,
                              "NameTokens" spanner.tokenlist generated always as (spanner.tokenize_fulltext("FirstName")) stored hidden,
                              PRIMARY KEY("Id")) INTERLEAVE IN "%PREFIX%_Root";

DROP SEARCH INDEX IF EXISTS "%PREFIX%_SearchIndex";
CREATE SEARCH INDEX "%PREFIX%_SearchIndex"
  ON "%PREFIX%_Singers"("NameTokens") ORDER BY "Id" WHERE "Id" IS NOT NULL
  WITH (sort_order_sharding=TRUE);
