template:

  name: "Iceberg_To_Oracle_Yaml"
  category: "BATCH"
  type: "YAML"
  display_name: "Iceberg to Oracle (YAML)"
  description: >
    The Iceberg to Oracle template is a batch pipeline that reads data from an Iceberg table
    and outputs the records to a Oracle database table.
  flex_container_name: "pipeline-yaml"
  yamlTemplateFile: "IcebergToOracle.yaml"
  filesToCopy: >
    {"main.py", "requirements.txt", "options/iceberg_options.yaml", "options/oracle_options.yaml"}
  contactInformation: "https://cloud.google.com/support"
  requirements: {
     "The Input Iceberg table must exist and be accessible through the provided catalog.",
     "The Output Oracle instance must exist and the target table must exist or be created."
   }
  streaming: false
  hidden: false

  options_file:
    - "iceberg_options"
    - "oracle_options"

  parameters:
    - iceberg_common_options
    - iceberg_read_options
    - oracle_common_options
    - oracle_write_options

pipeline:
  type: chain
  transforms:
    - type: ReadFromIceberg
      name: ReadFromIceberg
      config:
        table: {{ table }}
        catalog_name: {{ catalogName }}
        catalog_properties: {{ catalogProperties }}
        config_properties: {{ configProperties }}
        drop: {{ drop }}
        filter: {{ filter }}
        keep: {{ keep }}

    - type: WriteToOracle
      name: WriteToOracle
      config:
        driver_class_name: {{ driverClassName | default("oracle.jdbc.driver.OracleDriver")}}
        url: "{{ jdbcUrl }}"
        username: "{{ username }}"
        password: "{{ password }}"
        query: {{ writeQuery }}
        driver_jars: {{ driverJars }}
        connection_properties: {{ connectionProperties }}
        connection_init_sql: {{ connectionInitSql }}
        write_statement: {{ writeStatement }}
        table: {{ location }}
        batch_size: {{ batchSize }}
        autosharding: {{ autosharding }}
        type: {{ jdbcType | default("oracle") }}

options:
  streaming: false
