template:
  name: "MySQL_to_BigQuery_Yaml"
  category: "BATCH"
  type: "YAML"
  display_name: "MySQL to BigQuery (YAML)"
  description: >
    The MySQL to BigQuery template is a batch pipeline that copies data from a MySQL table into an existing BigQuery table. This pipeline uses JDBC to connect to MySQL.
  flex_container_name: "pipeline-yaml"
  yamlTemplateFile: "MySQLToBigQuery.yaml"
  filesToCopy: >
    {"main.py", "requirements.txt", "options/mysql_options.yaml", "options/bigquery_options.yaml"}
  contactInformation: "https://cloud.google.com/support"
  requirements: {
    "The MySQL instance and table must exist and be accessible from Dataflow workers.",
    "The target BigQuery dataset and table must exist."
  }
  streaming: false
  hidden: false

  options_file:
    - "mysql_options"
    - "bigquery_options"

  parameters:
    - mysql_common_options
    - mysql_read_options
    - bigquery_common_options
    - bigquery_write_options

pipeline:
  type: chain
  transforms:
    - type: ReadFromMySql
      name: ReadFromMySql
      config:
        url: "{{ jdbcUrl }}"
        username: "{{ username }}"
        password: "{{ password }}"
        query: {{ readQuery }}
        driver_jars: {{ driverJars }}
        connection_properties: {{ connectionProperties }}
        partition_column: {{ partitionColumn }}
        table: {{ location }}
        num_partitions: {{ numPartitions }}
        fetch_size: {{ fetchSize }}
        connection_init_sql: {{ connectionInitSql }}
        disable_auto_commit: {{ disableAutoCommit }}
        output_parallelization: {{ outputParallelization }}

    - type: WriteToBigQuery
      name: WriteToBigQuery
      config:
        table: {{ table }}
        create_disposition: {{ createDisposition | default('CREATE_IF_NEEDED') }}
        write_disposition: {{ writeDisposition | default('WRITE_APPEND') }}
        num_streams: {{ numStreams | default(1) }}

options:
  streaming: false
