template:
  name: "Postgres_To_Iceberg_Yaml"
  display_name: "Postgres to Iceberg (Yaml)"
  description: "A template for Postgres to Iceberg."
  flex_container_name: "postgres-to-iceberg-yaml"
  category: "BATCH"

  options_file:
    - "jdbc_options"
    - "iceberg_options"

  parameters:
    - jdbc_common_options
    - jdbc_read_options
    - iceberg_common_options
    - iceberg_write_options

pipeline:
  type: chain
  transforms:
    - type: ReadFromPostgres
      name: ReadFromPostgres
      config:
        driver_class_name: {{ driver_class_name | default("org.postgresql.Driver")}}
        url: {{ jdbc_url }}
        username: {{ username }}
        password: {{ password }}
        query: {{ read_query }}
        driver_jars: {{ driver_jars }}
        connection_properties: {{ connection_properties }}
        partition_column: {{ partition_column }}
        table: {{ location }}
        num_partitions: {{ num_partitions }}
        fetch_size: {{ fetch_size }}
        connection_init_sql: {{ connection_init_sql }}
        disable_auto_commit: {{ disable_auto_commit }}
        output_parallelization: {{ output_parallelization }}
        type: {{ jdbc_type | default("postgres") }}

    - type: WriteToIceberg
      name: WriteToIceberg
      config:
        table: {{ table }}
        catalog_name: {{ catalog_name }}
        catalog_properties: {{ catalog_properties }}
        config_properties: {{ config_properties }}
        drop: {{ drop }}
        keep: {{ keep }}
        only: {{ only }}
        partition_fields: {{ partition_fields }}
        table_properties: {{ table_properties }}
        triggering_frequency_seconds: {{ triggering_frequency_seconds }}

options:
  streaming: false