template:
  name: "Postgres_To_Iceberg_Yaml"
  display_name: "Postgres to Iceberg (Yaml)"
  description: "A template for Postgres to Iceberg."
  flex_container_name: "postgres-to-iceberg-yaml"
  category: "BATCH"

  options_file:
    - "postgres_options"
    - "iceberg_options"

  parameters:
    - postgres_common_options
    - postgres_read_options
    - iceberg_common_options
    - iceberg_write_options

pipeline:
  type: chain
  transforms:
    - type: ReadFromPostgres
      name: ReadFromPostgres
      config:
        driver_class_name: {{ driverClassName | default("org.postgresql.Driver")}}
        url: {{ jdbcUrl }}
        username: {{ username }}
        password: {{ password }}
        query: {{ readQuery }}
        driver_jars: {{ driverJars }}
        connection_properties: {{ connectionProperties }}
        partition_column: {{ partitionColumn }}
        table: {{ location }}
        num_partitions: {{ numPartitions }}
        fetch_size: {{ fetchSize }}
        connection_init_sql: {{ connectionInitSql }}
        disable_auto_commit: {{ disableAutoCommit }}
        output_parallelization: {{ outputParallelization }}
        type: {{ jdbcType | default("postgres") }}

    - type: WriteToIceberg
      name: WriteToIceberg
      config:
        table: {{ table }}
        catalog_name: {{ catalogName }}
        catalog_properties: {{ catalogProperties }}
        config_properties: {{ configProperties }}
        drop: {{ drop }}
        keep: {{ keep }}
        only: {{ only }}
        partition_fields: {{ partitionFields }}
        table_properties: {{ tableProperties }}
        triggering_frequency_seconds: {{ triggeringFrequencySeconds }}

options:
  streaming: false