template:

  name: "PubSub_To_AlloyDb_Yaml"
  category: "STREAMING"
  type: "YAML"
  display_name: "PubSub to AlloyDb (YAML)"
  description: >
    The PubSub to AlloyDb template is a streaming pipeline which ingests
    data from a PubSub topic, executes a user-defined mapping, and
    writes the resulting records to AlloyDb. Any errors which occur in the
    transformation of the data are written to a separate Pub/Sub topic.
  flex_container_name: "pipeline-yaml"
  yamlTemplateFile: "PubSubToAlloyDb.yaml"
  filesToCopy: >
    {"PubSubToAlloyDb.yaml", "main.py", "requirements.txt", "options/pubsub_options.yaml", "options/alloydb_options.yaml", "options/maptofields_options.yaml", "options/windowinto_options.yaml"}
  documentation: ""
  contactInformation: "https://cloud.google.com/support"
  requirements: {
    "The input Pub/Sub topic must exist.",
    "The mapToField Pub/Sub error topic must exist.",
    "The output AlloyDb instance must exist."
  }
  streaming: true
  hidden: false

  options_file:
    - "pubsub_options"
    - "maptofields_options"
    - "windowinto_options"
    - "alloydb_options"

  parameters:
    - pubsub_common_options
    - pubsub_read_options
    - maptofields_common_options
    - windowinto_common_options
    - alloydb_common_options
    - alloydb_write_options

    - name: "outputDeadLetterPubSubTopic"
      description: "Pub/Sub transformation error topic"
      help: "Pub/Sub error topic for failed transformation messages."
      example: "projects/your-project-id/topics/your-error-topic-name"
      required: true
      type: text
      order: 1


pipeline:
  type: composite
  transforms:
    - type: ReadFromPubSub
      name: ReadMessages
      config:
        subscription: {{ subscription }}
        format: {{ format }}
        schema: {{ schema }}
        attributes: {{ attributes }}
        attribute_map: {{ attributeMap }}
        id_attribute: {{ idAttribute }}
        timestamp_attribute: {{ timestampAttribute }}
    - type: MapToFields
      name: ConvertStringsToBytes
      input: ReadMessages
      config:
        language: {{ language }}
        fields: {{ fields }}
        error_handling:
          output: errors
    - type: WindowInto
      name: WindowInto
      input: ConvertStringsToBytes
      config:
        windowing: {{ windowing }}
    - type: WriteToPostgres
      name: WriteGoodMessagesToAlloyDb
      input: WindowInto
      config:
        driver_class_name: {{ driverClassName | default("org.postgresql.Driver") }}
        url: "{{ jdbcUrl }}"
        username: "{{ username }}"
        password: "{{ password }}"
        table: "{{ location }}"
        write_statement: "{{ writeStatement }}"
        batch_size: {{ batchSize }}
        autosharding: {{ autosharding }}
        type: "postgres"
        connection_properties: {{ connectionProperties }}
        connection_init_sql: {{ connectionInitSql }}
    - type: WriteToPubSub
      name: WriteTransformationErrorsToDeadLetterQueue
      input: ConvertStringsToBytes.errors
      config:
        topic: {{ outputDeadLetterPubSubTopic }}
        format: {{ format }}
        schema: |
          {{ schema }}

options:
  streaming: true
  use_public_ips: false
  network: {{ network }}
  subnetwork: {{ subnetwork }}
