template:
  name: "Word_Count_Yaml"
  category: "BATCH"
  type: "YAML"
  display_name: "Word Count (YAML)"
  description: >
    The Word Count template is a batch pipeline that reads text from Cloud Storage, splits lines into words, counts word occurrences, formats the results, and writes the output back to Cloud Storage.
  flex_container_name: "pipeline-yaml"
  yamlTemplateFile: "WordCount.yaml"
  filesToCopy: >
    {"main.py", "requirements.txt", "options/text_options.yaml"}
  contactInformation: "https://cloud.google.com/support"
  requirements: {
    "The input text file(s) on Cloud Storage must exist and be accessible.",
    "The output Cloud Storage directory must be accessible."
  }
  streaming: false
  hidden: false

  options_file:
    - "text_options"

  parameters:
    - text_write_options

pipeline:
  type: chain
  transforms:
    - type: ReadFromText
      name: ReadFromText
      config:
        path: gs://dataflow-samples/shakespeare/kinglear.txt

    - type: MapToFields
      name: "Split words"
      config:
        language: python
        fields:
          word:
            callable: |
              import re
              def my_mapping(row):
                return re.findall(r"[A-Za-z\']+", row.line.lower())
          value: "1"

    - type: Explode
      name: "Explode word arrays"
      config:
        fields:
          - word

    - type: Combine
      name: "Count words"
      config:
        group_by:
          - word
        combine:
          value: sum

    - type: MapToFields
      name: "Format output"
      config:
        language: python
        fields:
          output: "word + ': ' + str(value)"

    - type: WriteToText
      name: WriteToText
      config:
        path: "{{ outputPath }}"

options:
  streaming: false
