#
# Copyright (C) 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
#

# Autogenerated file. Do not edit.
<#list parameters as variable>
variable "${variable.name}" {
  type = ${variable.type?lower_case}
  description = "${variable.description}"
  <#if variable.defaultValue??>
  <#if variable.type == "STRING">default = "${variable.defaultValue}"<#else>default = ${variable.defaultValue}</#if>
  </#if>
}

</#list>

variable "transform_name_mapping" {
  type        = map(string)
  description = "Only applicable when updating a pipeline. Map of transform name prefixes of the job to be replaced with the corresponding name prefixes of the new job."
  default     = {}
}

variable "kms_key_name" {
  type        = string
  description = "The name for the Cloud KMS key for the job. Key format is: projects/PROJECT_ID/locations/LOCATION/keyRings/KEY_RING/cryptoKeys/KEY"
  default     = null
}

variable "network" {
  type        = string
  description = "The network to which VMs will be assigned. If it is not provided, \"default\" will be used."
  default     = null
}

variable "template_gcs_path" {
  type        = string
  description = "The Google Cloud Storage path to the Dataflow job template."
}

variable "temp_gcs_location" {
  type        = string
  description = "A writeable location on Google Cloud Storage for the Dataflow job to dump its temporary data."
}

variable "name" {
  type        = string
  description = "A unique name for the resource, required by Dataflow."
}

variable "labels" {
  type        = map(string)
  description = "User labels to be specified for the job. Keys and values should follow the restrictions specified in the labeling restrictions page. NOTE: This field is non-authoritative, and will only manage the labels present in your configuration.\n\t\t\t\tPlease refer to the field 'effective_labels' for all of the labels present on the resource."
  default     = {}
}

variable "ip_configuration" {
  type        = string
  description = "The configuration for VM IPs. Options are \"WORKER_IP_PUBLIC\" or \"WORKER_IP_PRIVATE\"."
  default     = null
}

variable "max_workers" {
  type        = number
  description = "The number of workers permitted to work on the job. More workers may improve processing speed at additional cost."
  default     = null
}

variable "on_delete" {
  type        = string
  description = "One of \"drain\" or \"cancel\". Specifies behavior of deletion during terraform destroy."
  default     = null
}

variable "skip_wait_on_job_termination" {
  type        = bool
  description = "If true, treat DRAINING and CANCELLING as terminal job states and do not wait for further changes before removing from terraform state and moving on. WARNING: this will lead to job name conflicts if you do not ensure that the job names are different, e.g. by embedding a release ID or by using a random_id."
  default     = null
}

variable "enable_streaming_engine" {
  type        = bool
  description = "Indicates if the job should use the streaming engine feature."
  default     = null
}

variable "zone" {
  type        = string
  description = "The zone in which the created job should run. If it is not provided, the provider zone is used."
  default     = null
}

variable "region" {
  type        = string
  description = "The region in which the created job should run."
  default     = null
}

variable "service_account_email" {
  type        = string
  description = "The Service Account email used to create the job."
  default     = null
}

variable "subnetwork" {
  type        = string
  description = "The subnetwork to which VMs will be assigned. Should be of the form \"regions/REGION/subnetworks/SUBNETWORK\"."
  default     = null
}

variable "machine_type" {
  type        = string
  description = "The machine type to use for the job."
  default     = null
}

resource "google_dataflow_job" "job" {
  parameters = {
<#list parameters as variable>
    ${variable.name} = <#if variable.type == "STRING">var.${variable.name}<#else>tostring(var.${variable.name})</#if>
</#list>
  }

  temp_gcs_location            = var.temp_gcs_location
  labels                       = var.labels
  name                         = var.name
  enable_streaming_engine      = var.enable_streaming_engine
  ip_configuration             = var.ip_configuration
  max_workers                  = var.max_workers
  on_delete                    = var.on_delete
  skip_wait_on_job_termination = var.skip_wait_on_job_termination
  zone                         = var.zone
  machine_type                 = var.machine_type
  region                       = var.region
  service_account_email        = var.service_account_email
  subnetwork                   = var.subnetwork
  transform_name_mapping       = var.transform_name_mapping
  kms_key_name                 = var.kms_key_name
  network                      = var.network
  template_gcs_path            = var.template_gcs_path
}

