steps:
#  - name: 'gcr.io/cloud-builders/docker'
#    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/db2testing/db2testimage', '.' ]
#    id: "build db2testimage"
  - name: 'cloudrunfordb2testimage'
    args:
      - 'run'
      - 'deploy'
      - 'cloudrunservice'
      - '--image'
      - 'us-central1-docker.pkg.dev/mlops-abed31/db2testing/db2testimage'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    id: "running on CR"
images:
  - 'us-central1-docker.pkg.dev/mlops-abed31/db2testing/db2testimage'

#gcloud projects add-iam-policy-binding mlops-abed31 \
#    --member=serviceAccount:476938344552@cloudbuild.gserviceaccount.com \
#    --role=roles/run.admin


#jean_legrais@cloudshell:~ (mlops-abed31)$ gcloud projects add-iam-policy-binding mlops-abed31 \
#    --member=serviceAccount:476938344552@cloudbuild.gserviceaccount.com \
#    --role=roles/run.admin
#Updated IAM policy for project [mlops-abed31].
#bindings:
#- members:
#  - serviceAccount:dlp-test@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:scotia-test-composer@mlops-abed31.iam.gserviceaccount.com
#  role: projects/mlops-abed31/roles/DLP_Inspect_Job_Role
#- members:
#  - serviceAccount:svc-auto-dlp-config@mlops-abed31.iam.gserviceaccount.com
#  role: projects/mlops-abed31/roles/custom_auto_dlp_config
#- members:
#  - serviceAccount:bqcx-476938344552-m819@gcp-sa-bigquery-condel.iam.gserviceaccount.com
#  role: projects/mlops-abed31/roles/custom_biglake_connection
#- members:
#  - serviceAccount:svc-dlp-cloud-function@mlops-abed31.iam.gserviceaccount.com
#  role: projects/mlops-abed31/roles/custom_dlp_bq
#- members:
#  - serviceAccount:data-replication-discovery@mlops-abed31.iam.gserviceaccount.com
#  role: projects/mlops-abed31/roles/data_replication_discovery
#- members:
#  - serviceAccount:ranger-gcp@mlops-abed31.iam.gserviceaccount.com
#  role: projects/mlops-abed31/roles/ranger_gcp
#- members:
#  - serviceAccount:ranger-gcp-test@mlops-abed31.iam.gserviceaccount.com
#  role: projects/mlops-abed31/roles/ranger_gcp_executor
#- members:
#  - serviceAccount:svc-data-foundations-deploy@mlops-abed31.iam.gserviceaccount.com
#  role: roles/artifactregistry.admin
#- members:
#  - serviceAccount:dbt-airflow-payments@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:dbt-artifact-test@mlops-abed31.iam.gserviceaccount.com
#  role: roles/artifactregistry.reader
#- members:
#  - serviceAccount:svc-data-foundations-deploy@mlops-abed31.iam.gserviceaccount.com
#  role: roles/artifactregistry.repoAdmin
#- members:
#  - serviceAccount:scotia-test-composer@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:service-476938344552@gcp-sa-artifactregistry.iam.gserviceaccount.com
#  role: roles/artifactregistry.serviceAgent
#- members:
#  - serviceAccount:dbt-artifact-test@mlops-abed31.iam.gserviceaccount.com
#  role: roles/artifactregistry.writer
#- members:
#  - serviceAccount:476938344552-compute@developer.gserviceaccount.com
#  - serviceAccount:dbt-airflow-payments@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:dbt-poc@scotia-gcp-edl.iam.gserviceaccount.com
#  - serviceAccount:dbt-test@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:rsimm-tf@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:scotia-test-composer@mlops-abed31.iam.gserviceaccount.com
#  role: roles/bigquery.admin
#- members:
#  - serviceAccount:bqcx-476938344552-94g2@gcp-sa-bigquery-condel.iam.gserviceaccount.com
#  - serviceAccount:svc-data-foundations-deploy@mlops-abed31.iam.gserviceaccount.com
#  role: roles/bigquery.connectionAdmin
#- members:
#  - serviceAccount:476938344552@cloudbuild.gserviceaccount.com
#  - serviceAccount:service-476938344552@gcp-sa-pubsub.iam.gserviceaccount.com
#  - serviceAccount:svc-data-foundations-deploy@mlops-abed31.iam.gserviceaccount.com
#  role: roles/bigquery.dataEditor
#- members:
#  - serviceAccount:dbt-poc-test@mlops-abed31.iam.gserviceaccount.com
#  role: roles/bigquery.dataOwner
#- members:
#  - user:jayesh.amarnani@badal.io
#  role: roles/bigquery.dataViewer
#- members:
#  - serviceAccount:dbt-poc-test@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:svc-data-foundations-deploy@mlops-abed31.iam.gserviceaccount.com
#  role: roles/bigquery.jobUser
#- members:
#  - serviceAccount:dbt-poc-test@mlops-abed31.iam.gserviceaccount.com
#  role: roles/bigquery.readSessionUser
#- members:
#  - serviceAccount:service-476938344552@gcp-sa-bigquerydatatransfer.iam.gserviceaccount.com
#  role: roles/bigquerydatatransfer.serviceAgent
#- members:
#  - serviceAccount:476938344552@cloudbuild.gserviceaccount.com
#  role: roles/cloudbuild.builds.builder
#- members:
#  - serviceAccount:cloudbuildrundb2@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:svc-data-foundations-deploy@mlops-abed31.iam.gserviceaccount.com
#  role: roles/cloudbuild.builds.editor
#- members:
#  - serviceAccount:service-476938344552@gcp-sa-cloudbuild.iam.gserviceaccount.com
#  role: roles/cloudbuild.serviceAgent
#- members:
#  - serviceAccount:svc-data-foundations-deploy@mlops-abed31.iam.gserviceaccount.com
#  role: roles/cloudfunctions.admin
#- members:
#  - serviceAccount:service-476938344552@gcf-admin-robot.iam.gserviceaccount.com
#  role: roles/cloudfunctions.serviceAgent
#- members:
#  - serviceAccount:rsimm-tf@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:svc-data-foundations-deploy@mlops-abed31.iam.gserviceaccount.com
#  - user:daniel@badal.io
#  role: roles/cloudkms.admin
#- members:
#  - serviceAccount:bq-476938344552@bigquery-encryption.iam.gserviceaccount.com
#  - serviceAccount:service-476938344552@gcf-admin-robot.iam.gserviceaccount.com
#  - serviceAccount:service-476938344552@gcp-sa-artifactregistry.iam.gserviceaccount.com
#  - serviceAccount:service-476938344552@gcp-sa-pubsub.iam.gserviceaccount.com
#  - serviceAccount:service-476938344552@gs-project-accounts.iam.gserviceaccount.com
#  - serviceAccount:svc-dlp-cloud-function@mlops-abed31.iam.gserviceaccount.com
#  role: roles/cloudkms.cryptoKeyEncrypterDecrypter
#- members:
#  - serviceAccount:bq-476938344552@bigquery-encryption.iam.gserviceaccount.com
#  - serviceAccount:service-476938344552@gcf-admin-robot.iam.gserviceaccount.com
#  - serviceAccount:service-476938344552@gcp-sa-artifactregistry.iam.gserviceaccount.com
#  - serviceAccount:service-476938344552@gcp-sa-pubsub.iam.gserviceaccount.com
#  - serviceAccount:service-476938344552@gs-project-accounts.iam.gserviceaccount.com
#  - serviceAccount:svc-dlp-cloud-function@mlops-abed31.iam.gserviceaccount.com
#  role: roles/cloudkms.cryptoKeyEncrypterDecrypterViaDelegation
#- members:
#  - serviceAccount:service-476938344552@gcp-sa-cloudkms.iam.gserviceaccount.com
#  role: roles/cloudkms.serviceAgent
#- members:
#  - serviceAccount:sftp-go-test@mlops-abed31.iam.gserviceaccount.com
#  role: roles/cloudsql.admin
#- members:
#  - serviceAccount:sftp-go-test@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:sftpgw-solution@mlops-abed31.iam.gserviceaccount.com
#  role: roles/cloudsql.client
#- members:
#  - serviceAccount:476938344552-compute@developer.gserviceaccount.com
#  - serviceAccount:sftp-go-test@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:sftpgw-solution@mlops-abed31.iam.gserviceaccount.com
#  role: roles/cloudsql.instanceUser
#- members:
#  - serviceAccount:service-476938344552@cloudcomposer-accounts.iam.gserviceaccount.com
#  role: roles/composer.ServiceAgentV2Ext
#- members:
#  - serviceAccount:service-476938344552@cloudcomposer-accounts.iam.gserviceaccount.com
#  role: roles/composer.serviceAgent
#- members:
#  - serviceAccount:scotia-test-composer@mlops-abed31.iam.gserviceaccount.com
#  role: roles/composer.worker
#- members:
#  - user:rahul.sorot@badal.io
#  role: roles/compute.admin
#- members:
#  - user:andrew.carroll@badal.io
#  - user:rahul.sorot@badal.io
#  role: roles/compute.osAdminLogin
#- members:
#  - serviceAccount:service-476938344552@compute-system.iam.gserviceaccount.com
#  role: roles/compute.serviceAgent
#- members:
#  - serviceAccount:dlp-test@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:scotia-test-composer@mlops-abed31.iam.gserviceaccount.com
#  role: roles/contactcenterinsights.editor
#- members:
#  - serviceAccount:service-476938344552@gcp-sa-contactcenterinsights.iam.gserviceaccount.com
#  role: roles/contactcenterinsights.serviceAgent
#- members:
#  - serviceAccount:service-476938344552@gcp-sa-gkenode.iam.gserviceaccount.com
#  role: roles/container.nodeServiceAgent
#- members:
#  - serviceAccount:service-476938344552@container-engine-robot.iam.gserviceaccount.com
#  role: roles/container.serviceAgent
#- members:
#  - serviceAccount:service-476938344552@containerregistry.iam.gserviceaccount.com
#  role: roles/containerregistry.ServiceAgent
#- members:
#  - serviceAccount:service-476938344552@gcp-sa-ktd-control.iam.gserviceaccount.com
#  role: roles/containerthreatdetection.serviceAgent
#- members:
#  - serviceAccount:svc-data-foundations-deploy@mlops-abed31.iam.gserviceaccount.com
#  role: roles/datacatalog.admin
#- members:
#  - serviceAccount:cdc-poc@mlops-abed31.iam.gserviceaccount.com
#  role: roles/datacatalog.tagEditor
#- members:
#  - user:jayesh.amarnani@badal.io
#  role: roles/datacatalog.tagTemplateUser
#- members:
#  - serviceAccount:476938344552@cloudbuild.gserviceaccount.com
#  - serviceAccount:cdc-poc@mlops-abed31.iam.gserviceaccount.com
#  role: roles/dataflow.admin
#- members:
#  - serviceAccount:service-476938344552@dataflow-service-producer-prod.iam.gserviceaccount.com
#  role: roles/dataflow.serviceAgent
#- members:
#  - serviceAccount:svc-bq-lineage-dataflow@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:svc-data-foundations-deploy@mlops-abed31.iam.gserviceaccount.com
#  role: roles/dataflow.worker
#- members:
#  - serviceAccount:service-476938344552@gcp-sa-dataplex.iam.gserviceaccount.com
#  role: roles/dataplex.serviceAgent
#- members:
#  - serviceAccount:scotia-test-composer@mlops-abed31.iam.gserviceaccount.com
#  role: roles/dataproc.editor
#- members:
#  - serviceAccount:service-476938344552@dataproc-accounts.iam.gserviceaccount.com
#  role: roles/dataproc.serviceAgent
#- members:
#  - serviceAccount:dbt-poc@scotia-gcp-edl.iam.gserviceaccount.com
#  role: roles/dataproc.worker
#- members:
#  - serviceAccount:svc-data-foundations-deploy@mlops-abed31.iam.gserviceaccount.com
#  role: roles/dlp.inspectTemplatesEditor
#- members:
#  - serviceAccount:dlp-test@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:scotia-test-composer@mlops-abed31.iam.gserviceaccount.com
#  role: roles/dlp.reader
#- members:
#  - serviceAccount:service-476938344552@dlp-api.iam.gserviceaccount.com
#  role: roles/dlp.serviceAgent
#- members:
#  - serviceAccount:dlp-test@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:scotia-test-composer@mlops-abed31.iam.gserviceaccount.com
#  role: roles/dlp.user
#- members:
#  - serviceAccount:476938344552-compute@developer.gserviceaccount.com
#  - serviceAccount:476938344552@cloudservices.gserviceaccount.com
#  - serviceAccount:cdc-poc@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:mlops-abed31@appspot.gserviceaccount.com
#  - serviceAccount:svc-bq-lineage-dataflow@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:svc-dlp-cloud-function@mlops-abed31.iam.gserviceaccount.com
#  role: roles/editor
#- members:
#  - serviceAccount:firebase-service-account@firebase-sa-management.iam.gserviceaccount.com
#  - serviceAccount:service-476938344552@gcp-sa-firebase.iam.gserviceaccount.com
#  role: roles/firebase.managementServiceAgent
#- members:
#  - serviceAccount:firebase-adminsdk-jxfuj@mlops-abed31.iam.gserviceaccount.com
#  role: roles/firebase.sdkAdminServiceAgent
#- members:
#  - serviceAccount:service-476938344552@firebase-rules.iam.gserviceaccount.com
#  role: roles/firebaserules.system
#- members:
#  - serviceAccount:rsimm-tf@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:svc-data-foundations-deploy@mlops-abed31.iam.gserviceaccount.com
#  - user:jayesh.amarnani@badal.io
#  role: roles/iam.roleAdmin
#- members:
#  - serviceAccount:rsimm-tf@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:svc-data-foundations-deploy@mlops-abed31.iam.gserviceaccount.com
#  role: roles/iam.serviceAccountAdmin
#- members:
#  - serviceAccount:476938344552@cloudbuild.gserviceaccount.com
#  - serviceAccount:dbt-poc@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:firebase-adminsdk-jxfuj@mlops-abed31.iam.gserviceaccount.com
#  - user:jayesh.amarnani@badal.io
#  role: roles/iam.serviceAccountTokenCreator
#- members:
#  - serviceAccount:476938344552@cloudbuild.gserviceaccount.com
#  - serviceAccount:svc-data-foundations-deploy@mlops-abed31.iam.gserviceaccount.com
#  role: roles/iam.serviceAccountUser
#- members:
#  - domain:badal.io
#  role: roles/iap.admin
#- members:
#  - user:jayesh.amarnani@badal.io
#  role: roles/iap.tunnelResourceAccessor
#- members:
#  - serviceAccount:svc-data-foundations-deploy@mlops-abed31.iam.gserviceaccount.com
#  - user:steven@badal.io
#  role: roles/logging.admin
#- members:
#  - serviceAccount:svc-auto-dlp-config@mlops-abed31.iam.gserviceaccount.com
#  role: roles/logging.logWriter
#- members:
#  - serviceAccount:sftpgw-solution@mlops-abed31.iam.gserviceaccount.com
#  role: roles/logging.serviceAgent
#- members:
#  - serviceAccount:bq-datalineage-test@dhruvkumar-test-qpl8f.iam.gserviceaccount.com
#  - serviceAccount:dbt-poc@mlops-abed31.iam.gserviceaccount.com
#  - user:alex.yun@badal.io
#  - user:andrew.carroll@badal.io
#  - user:artem.boiko@badal.io
#  - user:asad.siddiqui@badal.io
#  - user:colin.choi@badal.io
#  - user:daniel.vanderloo@badal.io
#  - user:daniel@badal.io
#  - user:dhruvkumar.patel@badal.io
#  - user:faith.uzoka@badal.io
#  - user:fatehpaul.dhaliwal@badal.io
#  - user:hossain.hassan@badal.io
#  - user:jayesh.amarnani@badal.io
#  - user:jean.legrais@badal.io
#  - user:jiny.song@badal.io
#  - user:jon.laberge@badal.io
#  - user:lamine.diop@badal.io
#  - user:mahmoud.shahin@badal.io
#  - user:ovo.okpubuluku@badal.io
#  - user:quinton.g@badal.io
#  - user:rahul.sorot@badal.io
#  - user:raphael.blankson@badal.io
#  - user:raymond@badal.io
#  - user:sebastien.g@badal.io
#  - user:sergei.i@badal.io
#  - user:sleighton@google.com
#  - user:steven@badal.io
#  - user:tim.d@badal.io
#  role: roles/owner
#- members:
#  - serviceAccount:cdc-poc@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:svc-data-foundations-deploy@mlops-abed31.iam.gserviceaccount.com
#  role: roles/pubsub.editor
#- members:
#  - serviceAccount:cloud-logs@system.gserviceaccount.com
#  role: roles/pubsub.publisher
#- members:
#  - serviceAccount:service-476938344552@gcp-sa-pubsub.iam.gserviceaccount.com
#  role: roles/pubsub.serviceAgent
#- members:
#  - serviceAccount:svc-dlp-cloud-function@mlops-abed31.iam.gserviceaccount.com
#  role: roles/pubsub.subscriber
#- members:
#  - serviceAccount:rsimm-tf@mlops-abed31.iam.gserviceaccount.com
#  role: roles/resourcemanager.organizationAdmin
#- members:
#  - serviceAccount:svc-data-foundations-deploy@mlops-abed31.iam.gserviceaccount.com
#  role: roles/resourcemanager.projectIamAdmin
#- members:
#  - domain:badal.io
#  - serviceAccount:476938344552@cloudbuild.gserviceaccount.com
#  role: roles/run.admin
#- members:
#  - serviceAccount:service-476938344552@serverless-robot-prod.iam.gserviceaccount.com
#  role: roles/run.serviceAgent
#- members:
#  - serviceAccount:sftpgw-trigger@mlops-abed31.iam.gserviceaccount.com
#  role: roles/secretmanager.secretAccessor
#- members:
#  - serviceAccount:service-476938344552@service-networking.iam.gserviceaccount.com
#  role: roles/servicenetworking.serviceAgent
#- members:
#  - serviceAccount:dbt-poc@mlops-abed31.iam.gserviceaccount.com
#  role: roles/serviceusage.serviceUsageConsumer
#- members:
#  - serviceAccount:rsimm-tf@mlops-abed31.iam.gserviceaccount.com
#  role: roles/source.admin
#- members:
#  - serviceAccount:dlp-test@mlops-abed31.iam.gserviceaccount.com
#  role: roles/speech.client
#- members:
#  - serviceAccount:476938344552-compute@developer.gserviceaccount.com
#  - serviceAccount:cdc-poc@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:ldm-storage-account@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:rsimm-tf@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:sftp-go-test@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:sftpgw-solution@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:sftpgw-trigger@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:svc-data-foundations-deploy@mlops-abed31.iam.gserviceaccount.com
#  role: roles/storage.admin
#- members:
#  - serviceAccount:b2p241-db2-mssql@mlops-abed31.iam.gserviceaccount.com
#  - serviceAccount:dbt-poc-test@mlops-abed31.iam.gserviceaccount.com
#  - user:jayesh.amarnani@badal.io
#  role: roles/storage.objectAdmin
#- members:
#  - serviceAccount:bqcx-476938344552-3wnc@gcp-sa-bigquery-condel.iam.gserviceaccount.com
#  - serviceAccount:bqcx-476938344552-94g2@gcp-sa-bigquery-condel.iam.gserviceaccount.com
#  - serviceAccount:bqcx-476938344552-m819@gcp-sa-bigquery-condel.iam.gserviceaccount.com
#  role: roles/storage.objectViewer
#- members:
#  - user:jayesh.amarnani@badal.io
#  role: roles/viewer
#- members:
#  - serviceAccount:service-476938344552@gcp-sa-vpcaccess.iam.gserviceaccount.com
#  role: roles/vpcaccess.serviceAgent
#- members:
#  - serviceAccount:service-476938344552@gcp-sa-websecurityscanner.iam.gserviceaccount.com
#  role: roles/websecurityscanner.serviceAgent
#etag: BwXsbzSGYno=
#version: 1