CREATE SCHEMA "my_schema";

CREATE SEQUENCE my_schema."MySequence" BIT_REVERSED_POSITIVE;

CREATE TABLE my_schema."MyTable" (
	"id"                                    bigint NOT NULL,
	"data"                                  text,
	PRIMARY KEY ("id")
);

CREATE INDEX "my_schema_MyTable_data_idx" ON my_schema."MyTable"("data");

CREATE VIEW my_schema."MyView" SQL SECURITY INVOKER AS SELECT t.id FROM my_schema."MyTable" t;

ALTER TABLE my_schema."MyTable" ADD COLUMN "tokens" spanner.tokenlist HIDDEN GENERATED ALWAYS AS (spanner.tokenize_substring("data")) STORED;

CREATE SEARCH INDEX "MySearchIdx" ON my_schema."MyTable"("tokens");

ALTER DATABASE "%DATABASE_NAME%" SET spanner.optimizer_version = 1;

-- Roles
CREATE ROLE "hr_manager";
CREATE ROLE "sales_manager";

CREATE TABLE "Users" (
	"first_name"                            character varying,
	"last_name"                             character varying(5),
	"age"                                   bigint,
	PRIMARY KEY ("first_name", "last_name")
);

-- All Datatypes
CREATE TABLE "AllTYPES" (
	"id"                                    bigint NOT NULL,
	"first_name"                            character varying,
	"last_name"                             character varying(5),
	"bool_field"                            boolean,
	"int_field"                             bigint,
	"float32_field"                         real,
	"float64_field"                         double precision,
	"string_field"                          text,
	"bytes_field"                           bytea,
	"timestamp_field"                       timestamp with time zone,
	"numeric_field"                         numeric,
	"date_field"                            date,
	"json_field"                            jsonb,
	"uuid_field"                            uuid,

	"arr_bool_field"                        boolean[],
	"arr_int_field"                         bigint[],
	"arr_float32_field"                     real[],
	"arr_float64_field"                     double precision[],
	"arr_string_field"                      character varying[],
	"arr_bytes_field"                       bytea[],
	"arr_timestamp_field"                   timestamp with time zone[],
	"arr_date_field"                        date[],
	"arr_numeric_field"                     numeric[],
	"arr_json_field"                        jsonb[],
	"arr_uuid_field"                        uuid[],

	PRIMARY KEY ("first_name", "last_name", "id")
)
INTERLEAVE IN PARENT "Users" ON DELETE CASCADE;

CREATE TABLE "PK_Float64" ( "key" double precision, "val" bigint, PRIMARY KEY ("key") );
CREATE TABLE "PK_Uuid" ( "key" uuid, "val" bigint, PRIMARY KEY ("key") );

-- Generated and Identity Primary Keys
CREATE TABLE "PK_AutoUuid" (
	"id" uuid DEFAULT gen_random_uuid(),
	"val" bigint,
	PRIMARY KEY ("id")
);

CREATE TABLE "PK_Generated" (
	"id" bigint NOT NULL,
	"gen_id" bigint GENERATED ALWAYS AS ("id" + 1) STORED,
	"val" bigint,
	PRIMARY KEY ("gen_id")
);

CREATE TABLE "PK_Identity" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE),
	"val" bigint,
	PRIMARY KEY ("id")
);

-- Foreign Keys
CREATE TABLE "Ref" (
	"id1"                                   bigint,
	"id2"                                   bigint,
	PRIMARY KEY ("id1", "id2")
);
CREATE TABLE "Child" (
	"id1"                                   bigint,
	"id2"                                   bigint,
	"id3"                                   bigint,
	PRIMARY KEY ("id1", "id2", "id3")
) 
INTERLEAVE IN PARENT "Ref";
ALTER TABLE "Child" ADD CONSTRAINT "fk1" FOREIGN KEY ("id1") REFERENCES "Ref" ("id1");

-- Sequences
CREATE SEQUENCE mysequence BIT_REVERSED_POSITIVE;
CREATE SEQUENCE countersequence BIT_REVERSED_POSITIVE START COUNTER WITH 100;

CREATE TABLE "Authors" (
	"author_id"                             bigint NOT NULL DEFAULT nextval('mysequence'),
	"name"                                  text,
	"author_type"                           character varying(20) DEFAULT 'USER',
	"placement_key"                         text,
	"hidden_col"                            text HIDDEN,
	"score"                                 bigint GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE START COUNTER WITH 100),
	PRIMARY KEY ("author_id")
);

CREATE TABLE "Articles" (
	"author_id"                             bigint NOT NULL,
	"article_id"                            bigint NOT NULL DEFAULT nextval('countersequence'),
	"title"                                 text,
	"content"                               text,
	"tags"                                  character varying[],
	"publish_date"                          timestamp with time zone,
	"status"                                character varying(20),
	PRIMARY KEY ("author_id", "article_id")
)
INTERLEAVE IN PARENT "Authors" ON DELETE CASCADE;

-- Indexes
CREATE INDEX "AuthorNameIdx" ON "Authors"("name" DESC NULLS FIRST);
CREATE UNIQUE INDEX "UniqueArticleTitle" ON "Articles"("title" ASC NULLS LAST) INCLUDE ("publish_date");
CREATE UNIQUE INDEX "NullFilteredIdxPG" ON "Articles"("status") WHERE "status" IS NOT NULL;

-- Grants
GRANT SELECT ON TABLE "Authors" TO "hr_manager";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "Articles" TO "sales_manager";

-- Views
CREATE VIEW "AuthorStatsView" SQL SECURITY INVOKER AS SELECT "Articles"."author_id", COUNT(*) as "num_articles" FROM "Articles" GROUP BY "Articles"."author_id";

-- Change Streams
CREATE CHANGE STREAM "AllStream" FOR ALL WITH (retention_period='7d', value_capture_type='OLD_AND_NEW_VALUES');
