ALTER DATABASE `%DATABASE_NAME%` SET OPTIONS ( optimizer_version = 1, default_leader = 'us-east4' );

CREATE PLACEMENT `my_placement` OPTIONS(instance_partition='default');

-- With Named Schema
CREATE SCHEMA `my_schema`;

CREATE SEQUENCE `my_schema`.`MySequence` OPTIONS (sequence_kind = 'bit_reversed_positive');

CREATE TABLE `my_schema`.`MyTable` (
	`id`                                    INT64 NOT NULL,
	`data`                                  STRING(MAX),
) PRIMARY KEY (`id` ASC);

CREATE INDEX `my_schema`.`MyTable_data_idx` ON `my_schema`.`MyTable`(`data` ASC);

CREATE VIEW `my_schema`.`MyView` SQL SECURITY INVOKER AS SELECT t.id FROM `my_schema`.`MyTable` t;

ALTER TABLE `my_schema`.`MyTable` ADD COLUMN `tokens` TOKENLIST AS (TOKENIZE_SUBSTRING(data)) HIDDEN;

CREATE PROPERTY GRAPH `my_schema`.`MyGraph`
  NODE TABLES (`my_schema`.`MyTable`);

CREATE SEARCH INDEX `my_schema`.`MySearchIdx` ON `my_schema`.`MyTable`(`tokens`);

-- Without Named Schema

-- Roles
CREATE ROLE `hr_manager`;
CREATE ROLE `sales_manager`;

-- Tables with interleaving
CREATE TABLE `Users` (
	`first_name`                            STRING(MAX),
	`last_name`                             STRING(5),
	`age`                                   INT64,
) PRIMARY KEY (`first_name` ASC, `last_name` DESC);

-- All Datatypes
CREATE TABLE `AllTYPES` (
	`first_name`                            STRING(MAX),
	`last_name`                             STRING(5),
	`id`                                    INT64 NOT NULL,
	`bool_field`                            BOOL,
	`int64_field`                           INT64,
	`float32_field`                         FLOAT32,
	`float64_field`                         FLOAT64,
	`numeric_field`                         NUMERIC,
	`string_field`                          STRING(MAX),
	`bytes_field`                           BYTES(MAX),
	`timestamp_field`                       TIMESTAMP,
	`date_field`                            DATE,
	`json_field`                            JSON,
	`uuid_field`                            UUID,

	`arr_bool_field`                        ARRAY<BOOL>,
	`arr_int64_field`                       ARRAY<INT64>,
	`arr_float32_field`                     ARRAY<FLOAT32>,
	`arr_float64_field`                     ARRAY<FLOAT64>,
	`arr_numeric_field`                     ARRAY<NUMERIC>,
	`arr_string_field`                      ARRAY<STRING(MAX)>,
	`arr_bytes_field`                       ARRAY<BYTES(MAX)>,
	`arr_timestamp_field`                   ARRAY<TIMESTAMP>,
	`arr_date_field`                        ARRAY<DATE>,
	`arr_json_field`                        ARRAY<JSON>,
	`arr_uuid_field`                        ARRAY<UUID>,
) PRIMARY KEY (`first_name` ASC, `last_name` DESC, `id` ASC),
INTERLEAVE IN PARENT `Users` ON DELETE CASCADE;

-- Comprehensive Primary Key Types
CREATE TABLE `PK_Bool` ( `key` BOOL, `val` INT64 ) PRIMARY KEY (`key` ASC);
CREATE TABLE `PK_Int64` ( `key` INT64, `val` INT64 ) PRIMARY KEY (`key` ASC);
CREATE TABLE `PK_Float64` ( `key` FLOAT64, `val` INT64 ) PRIMARY KEY (`key` ASC);
CREATE TABLE `PK_Numeric` ( `key` NUMERIC, `val` INT64 ) PRIMARY KEY (`key` ASC);
CREATE TABLE `PK_String` ( `key` STRING(MAX), `val` INT64 ) PRIMARY KEY (`key` ASC);
CREATE TABLE `PK_Bytes` ( `key` BYTES(MAX), `val` INT64 ) PRIMARY KEY (`key` ASC);
CREATE TABLE `PK_Date` ( `key` DATE, `val` INT64 ) PRIMARY KEY (`key` ASC);
CREATE TABLE `PK_Timestamp` ( `key` TIMESTAMP, `val` INT64 ) PRIMARY KEY (`key` ASC);
CREATE TABLE `PK_Uuid` ( `key` UUID, `val` INT64 ) PRIMARY KEY (`key` ASC);

-- Generated and Identity Primary Keys
CREATE TABLE `PK_AutoUuid` (
	`id` UUID DEFAULT (NEW_UUID()),
	`val` INT64
) PRIMARY KEY (`id` ASC);

CREATE TABLE `PK_Generated` (
	`id` INT64 NOT NULL,
	`gen_id` INT64 AS (`id` + 1) STORED,
	`val` INT64
) PRIMARY KEY (`gen_id` ASC);

CREATE TABLE `PK_Identity` (
	`id` INT64 GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE),
	`val` INT64
) PRIMARY KEY (`id` ASC);

-- Foreign Keys
CREATE TABLE `Ref` (
	`id1`                                   INT64,
	`id2`                                   INT64,
) PRIMARY KEY (`id1` ASC, `id2` ASC);

CREATE TABLE `Child` (
	`id1`                                   INT64,
	`id2`                                   INT64,
	`id3`                                   INT64,
) PRIMARY KEY (`id1` ASC, `id2` ASC, `id3` ASC),
INTERLEAVE IN PARENT `Ref`;

ALTER TABLE `Child` ADD CONSTRAINT `fk1` FOREIGN KEY (`id1`) REFERENCES `Ref` (`id1`);
ALTER TABLE `Child` ADD CONSTRAINT `fk2` FOREIGN KEY (`id2`) REFERENCES `Ref` (`id2`);

-- Sequences
CREATE SEQUENCE `MySequence` OPTIONS (sequence_kind='bit_reversed_positive');
CREATE SEQUENCE `CounterSequence` OPTIONS (sequence_kind='bit_reversed_positive', start_with_counter=100);
CREATE SEQUENCE `SkipRangeSequence` OPTIONS (sequence_kind='bit_reversed_positive', skip_range_min=1, skip_range_max=1000);

-- Comprehensive Schema Features
CREATE TABLE `Authors` (
	`author_id`                             INT64 NOT NULL DEFAULT (GET_NEXT_SEQUENCE_VALUE(SEQUENCE MySequence)),
	`name`                                  STRING(MAX),
	`author_type`                           STRING(20) DEFAULT ('USER'),
	`placement_key`                         STRING(MAX),
	`hidden_col`                            STRING(MAX) HIDDEN,
	`score`                                 INT64 GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE SKIP RANGE 1, 1000 START COUNTER WITH 100),
) PRIMARY KEY (`author_id` ASC);

CREATE TABLE `Articles` (
	`author_id`                             INT64 NOT NULL,
	`article_id`                            INT64 NOT NULL DEFAULT (GET_NEXT_SEQUENCE_VALUE(SEQUENCE CounterSequence)),
	`title`                                 STRING(MAX),
	`content`                               STRING(MAX),
	`tags`                                  ARRAY<STRING(MAX)>,
	`embeddings`                            ARRAY<FLOAT32>(vector_length=>3),
	`publish_date`                          TIMESTAMP OPTIONS (allow_commit_timestamp=TRUE),
	`status`                                STRING(20),
	`search_tokens`                         TOKENLIST AS (TOKENIZE_FULLTEXT(`content`)) HIDDEN,
	CONSTRAINT `status_check` CHECK (`status` IN ('DRAFT', 'PUBLISHED')),
) PRIMARY KEY (`author_id` ASC, `article_id` ASC),
INTERLEAVE IN PARENT `Authors` ON DELETE CASCADE;

CREATE TABLE `Comments` (
	`author_id`                             INT64 NOT NULL,
	`article_id`                            INT64 NOT NULL,
	`comment_id`                            INT64 NOT NULL,
	`text`                                  STRING(MAX),
) PRIMARY KEY (`author_id` ASC, `article_id` ASC, `comment_id` ASC),
INTERLEAVE IN PARENT `Articles`;

CREATE TABLE `GraphNodes` (
	`node_key`                              INT64,
	`dynamic_label_col`                     STRING(MAX),
) PRIMARY KEY (`node_key` ASC);

CREATE TABLE `GraphEdges` (
	`edge_key`                              INT64,
	`source_node`                           INT64,
	`dest_node`                             INT64,
) PRIMARY KEY (`edge_key` ASC);

-- Indexes
CREATE INDEX `AuthorNameIdx` ON `Authors`(`name` DESC);
CREATE UNIQUE INDEX `UniqueArticleTitle` ON `Articles`(`title` ASC) STORING (`publish_date`);
CREATE UNIQUE NULL_FILTERED INDEX `NullFilteredIdx` ON `Articles`(`status` ASC);
CREATE VECTOR INDEX `ArticlesEmbeddingIdx` ON `Articles`(`embeddings`) WHERE `embeddings` IS NOT NULL OPTIONS (distance_type='COSINE');
CREATE SEARCH INDEX `ArticlesSearchIdx` ON `Articles`(`search_tokens`);

-- Grants
GRANT SELECT ON TABLE `Authors` TO ROLE `hr_manager`;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE `Articles` TO ROLE `sales_manager`;

-- Views
CREATE VIEW `AuthorStatsView` SQL SECURITY INVOKER AS SELECT `Articles`.`author_id`, COUNT(*) as `num_articles` FROM `Articles` GROUP BY `Articles`.`author_id`;
CREATE VIEW `DefinerView` SQL SECURITY DEFINER AS SELECT `Articles`.`title` FROM `Articles` WHERE `Articles`.`status` = 'PUBLISHED';

-- Change Streams
CREATE CHANGE STREAM `AllStream` FOR ALL OPTIONS (retention_period="7d", value_capture_type="OLD_AND_NEW_VALUES");
CREATE CHANGE STREAM `TableStream` FOR `Authors`, `Articles`(`title`, `content`), `Comments`();

-- Property Graphs
CREATE PROPERTY GRAPH `DynamicGraph`
NODE TABLES(
`GraphNodes` AS `node_alias`
 KEY (`node_key`)
LABEL `dummy_label` PROPERTIES(`node_key`)
LABEL `dynamic_label` NO PROPERTIES
DYNAMIC LABEL(`dynamic_label_col`)
)
EDGE TABLES(
`GraphEdges` AS `edge_alias`
 KEY (`edge_key`)
SOURCE KEY(`source_node`) REFERENCES `node_alias`(`node_key`) DESTINATION KEY(`dest_node`) REFERENCES `node_alias`(`node_key`)
LABEL `edge_label` NO PROPERTIES
);

-- Models
CREATE MODEL `m_simpleModel_text_bison`
INPUT ( `prompt` STRING(MAX) )
OUTPUT ( `content` STRING(MAX) )
REMOTE OPTIONS (endpoint='//aiplatform.googleapis.com/projects/%PROJECT_ID%/locations/us-central1/publishers/google/models/text-bison');

-- Functions (UDFs)
CREATE FUNCTION `my_schema`.`MyCustomFunction`(`input_val` INT64) RETURNS INT64 AS (`input_val` * 2);


