SELECT ID,APP_ID FROM TESTDB.TESTS.OBJ_BASE;
SELECT ID,ACTIVITY_ID FROM TESTDB.TESTS.ERROR;
SELECT OBJ1_ID,OBJ2_ID FROM TESTDB.TESTS.OBJ_OBJ_REL;
SELECT OBJ_ID,BATCH_ID FROM TESTDB.TESTS.TRANSACTION_BASE;
SELECT OBJ_ID,PARTY_ID FROM TESTDB.TESTS.TRANSMISSION_BASE;
SELECT OBJ_ID,PAYMENT_TYPE FROM TESTDB.TESTS.TXN_PAYMENT_BASE;