{
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "id": "cloudidentity:v1",
  "name": "cloudidentity",
  "canonicalName": "Cloud Identity",
  "version": "v1",
  "revision": "0",
  "title": "Cloud Identity API",
  "description": "API for provisioning and managing identity resources.",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": "https://cloud.google.com/identity/",
  "protocol": "rest",
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "servicePath": "",
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "batchPath": "batch",
  "version_module": true,
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-identity.devices.lookup": {
          "description": "See your device details"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "View and manage your data across Google Cloud Platform services"
        }
      }
    }
  },
  "resources": {
    "devices": {
      "methods": {
        "create": {
          "id": "cloudidentity.devices.create",
          "path": "v1/devices",
          "flatPath": "v1/devices",
          "httpMethod": "POST",
          "description": "Creates a device. Only company-owned device may be created."
        },
        "get": {
          "id": "cloudidentity.devices.get",
          "path": "v1/{+name}",
          "flatPath": "v1/devices/{devicesId}",
          "httpMethod": "GET",
          "description": "Retrieves the specified device."
        },
        "list": {
          "id": "cloudidentity.devices.list",
          "path": "v1/devices",
          "flatPath": "v1/devices",
          "httpMethod": "GET",
          "description": "Lists\/Searches devices."
        },
        "patch": {
          "id": "cloudidentity.devices.patch",
          "path": "v1/{+name}",
          "flatPath": "v1/devices/{devicesId}",
          "httpMethod": "PATCH",
          "description": "Updates the specified device."
        },
        "delete": {
          "id": "cloudidentity.devices.delete",
          "path": "v1/{+name}",
          "flatPath": "v1/devices/{devicesId}",
          "httpMethod": "DELETE",
          "description": "Deletes the specified device."
        },
        "ring": {
          "id": "cloudidentity.devices.ring",
          "path": "v1/{+name}:ring",
          "flatPath": "v1/devices:ring",
          "httpMethod": "POST",
          "description": "Rings the specified device. A device typically has the functionality to attract user attention by providing an audio or vibration signal. This method enables the caller to activate that signal."
        },
        "lock": {
          "id": "cloudidentity.devices.lock",
          "path": "v1/{+name}:lock",
          "flatPath": "v1/devices:lock",
          "httpMethod": "POST",
          "description": "Locks the specified device, without signing out the user. Locking a device will require the user to enter their passcode, biometric or other device- level authentication in order to use the device again."
        },
        "resetPin": {
          "id": "cloudidentity.devices.resetPin",
          "path": "v1/{+name}:resetPin",
          "flatPath": "v1/devices:resetPin",
          "httpMethod": "POST",
          "description": "Resets the specified device's pin"
        },
        "wipe": {
          "id": "cloudidentity.devices.wipe",
          "path": "v1/{+name}:wipe",
          "flatPath": "v1/devices/{devicesId}:wipe",
          "httpMethod": "POST",
          "description": "Wipes all data on the specified device."
        },
        "cancelWipe": {
          "id": "cloudidentity.devices.cancelWipe",
          "path": "v1/{+name}:cancelWipe",
          "flatPath": "v1/devices/{devicesId}:cancelWipe",
          "httpMethod": "POST",
          "description": "Cancels an unfinished device wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped. This operation is possible when the device is in a \"pending wipe\" state. The device enters the \"pending wipe\" state when a wipe device command is issued, but has not yet been sent to the device. The cancel wipe will fail if the wipe command has already been issued to the device."
        }
      }
      ,
      "resources": {
        "deviceUsers": {
          "methods": {
            "get": {
              "id": "cloudidentity.devices.deviceUsers.get",
              "path": "v1/{+name}",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "httpMethod": "GET",
              "description": "Retrieves the specified DeviceUser"
            },
            "list": {
              "id": "cloudidentity.devices.deviceUsers.list",
              "path": "v1/{+parent}/deviceUsers",
              "flatPath": "v1/devices/{devicesId}/deviceUsers",
              "httpMethod": "GET",
              "description": "Lists\/Searches DeviceUsers."
            },
            "patch": {
              "id": "cloudidentity.devices.deviceUsers.patch",
              "path": "v1/{+name}",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "httpMethod": "PATCH",
              "description": "Updates the specified DeviceUser."
            },
            "delete": {
              "id": "cloudidentity.devices.deviceUsers.delete",
              "path": "v1/{+name}",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "httpMethod": "DELETE",
              "description": "Deletes the specified DeviceUser. This also revokes the user's access to device data."
            },
            "lookup": {
              "id": "cloudidentity.devices.deviceUsers.lookup",
              "path": "v1/{+parent}:lookup",
              "flatPath": "v1/devices/{devicesId}/deviceUsers:lookup",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices.lookup"
              ],
              "description": "Looks up resource names of the DeviceUsers associated with the caller's credentials, as well as the properties provided in the request. This method must be called with end-user credentials with the scope: https:\/\/www.googleapis.com\/auth\/cloud-identity.devices.lookup If multiple properties are provided, only DeviceUsers having all of these properties are considered as matches - i.e. the query behaves like an AND. Different platforms require different amounts of i[...]"
            },
            "collectBugReport": {
              "id": "cloudidentity.devices.deviceUsers.collectBugReport",
              "path": "v1/{+name}:collectBugReport",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:collectBugReport",
              "httpMethod": "POST",
              "description": "Collects bug report on the specified device, which can be later downloaded from [Admin Console](https:\/\/admin.google.com)."
            },
            "sync": {
              "id": "cloudidentity.devices.deviceUsers.sync",
              "path": "v1/{+name}:sync",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:sync",
              "httpMethod": "POST",
              "description": "Syncs the device to company's policy"
            },
            "signout": {
              "id": "cloudidentity.devices.deviceUsers.signout",
              "path": "v1/{+name}:signout",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:signout",
              "httpMethod": "POST",
              "description": "Signs out the user from the specified device"
            },
            "approve": {
              "id": "cloudidentity.devices.deviceUsers.approve",
              "path": "v1/{+name}:approve",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve",
              "httpMethod": "POST",
              "description": "Approves device to access user data."
            },
            "block": {
              "id": "cloudidentity.devices.deviceUsers.block",
              "path": "v1/{+name}:block",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block",
              "httpMethod": "POST",
              "description": "Blocks device from accessing user data"
            },
            "unenroll": {
              "id": "cloudidentity.devices.deviceUsers.unenroll",
              "path": "v1/{+name}:unenroll",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:unenroll",
              "httpMethod": "POST",
              "description": "Unenrolls the user from Advanced Windows Management without affecting their user account."
            },
            "wipe": {
              "id": "cloudidentity.devices.deviceUsers.wipe",
              "path": "v1/{+name}:wipe",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe",
              "httpMethod": "POST",
              "description": "Wipes the user's account on a device. Other data on the device that is not associated with the user's work account is not affected. For example, if a Gmail app is installed on a device that is used for personal and work purposes, and the user is logged in to the Gmail app with their personal account as well as their work account, wiping the \"deviceUser\" by their work administrator will not affect their personal account within Gmail or other apps such as Photos."
            },
            "cancelWipe": {
              "id": "cloudidentity.devices.deviceUsers.cancelWipe",
              "path": "v1/{+name}:cancelWipe",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe",
              "httpMethod": "POST",
              "description": "Cancels an unfinished user account wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped."
            }
          }
          ,
          "resources": {
            "endpointApps": {
              "methods": {
                "list": {
                  "id": "cloudidentity.devices.deviceUsers.endpointApps.list",
                  "path": "v1/{+parent}/endpointApps",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/endpointApps",
                  "httpMethod": "GET",
                  "description": "Lists all managed apps intalled on the device."
                }
              }
            },
            "clientStates": {
              "methods": {
                "get": {
                  "id": "cloudidentity.devices.deviceUsers.clientStates.get",
                  "path": "v1/{+name}",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "httpMethod": "GET",
                  "description": "Gets the client state for the device user"
                },
                "list": {
                  "id": "cloudidentity.devices.deviceUsers.clientStates.list",
                  "path": "v1/{+parent}/clientStates",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates",
                  "httpMethod": "GET",
                  "description": "Lists the client states for the given search query."
                },
                "patch": {
                  "id": "cloudidentity.devices.deviceUsers.clientStates.patch",
                  "path": "v1/{+name}",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "httpMethod": "PATCH",
                  "description": "Updates the client state for the device user"
                }
              }
            }
          }
        }
      }
    },
    "groups": {
      "methods": {
        "create": {
          "id": "cloudidentity.groups.create",
          "path": "v1/groups",
          "flatPath": "v1/groups",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Creates a Group."
        },
        "get": {
          "id": "cloudidentity.groups.get",
          "path": "v1/{+name}",
          "flatPath": "v1/groups/{groupsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Retrieves a `Group`."
        },
        "patch": {
          "id": "cloudidentity.groups.patch",
          "path": "v1/{+name}",
          "flatPath": "v1/groups/{groupsId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Updates a `Group`."
        },
        "delete": {
          "id": "cloudidentity.groups.delete",
          "path": "v1/{+name}",
          "flatPath": "v1/groups/{groupsId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Deletes a `Group`."
        },
        "lookup": {
          "id": "cloudidentity.groups.lookup",
          "path": "v1/groups:lookup",
          "flatPath": "v1/groups:lookup",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Looks up the [resource name](https:\/\/cloud.google.com\/apis\/design\/resource_names) of a `Group` by its `EntityKey`."
        },
        "search": {
          "id": "cloudidentity.groups.search",
          "path": "v1/groups:search",
          "flatPath": "v1/groups:search",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Searches for `Group`s matching a specified query."
        },
        "list": {
          "id": "cloudidentity.groups.list",
          "path": "v1/groups",
          "flatPath": "v1/groups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Lists the `Group`s under a customer or namespace."
        }
      }
      ,
      "resources": {
        "memberships": {
          "methods": {
            "create": {
              "id": "cloudidentity.groups.memberships.create",
              "path": "v1/{+parent}/memberships",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Creates a `Membership`."
            },
            "get": {
              "id": "cloudidentity.groups.memberships.get",
              "path": "v1/{+name}",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Retrieves a `Membership`."
            },
            "patch": {
              "id": "cloudidentity.groups.memberships.patch",
              "path": "v1/{+name}",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Updates a `Membership`."
            },
            "delete": {
              "id": "cloudidentity.groups.memberships.delete",
              "path": "v1/{+name}",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Deletes a `Membership`."
            },
            "lookup": {
              "id": "cloudidentity.groups.memberships.lookup",
              "path": "v1/{+parent}/memberships:lookup",
              "flatPath": "v1/groups/{groupsId}/memberships:lookup",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Looks up the [resource name](https:\/\/cloud.google.com\/apis\/design\/resource_names) of a `Membership` by its `EntityKey`."
            },
            "list": {
              "id": "cloudidentity.groups.memberships.list",
              "path": "v1/{+parent}/memberships",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Lists the `Membership`s within a `Group`."
            },
            "modifyMembershipRoles": {
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles",
              "path": "v1/{+name}:modifyMembershipRoles",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Modifies the `MembershipRole`s of a `Membership`."
            }
          }
        }
      }
    }
  },
  "basePath": ""
}