CREATE TABLE AccountRoles (
  role_id INT64 NOT NULL,
  role_name STRING(MAX)
) PRIMARY KEY(role_id);

CREATE TABLE `ORDER` (
  `SELECT` STRING(MAX) NOT NULL,
  `GROUP` STRING(MAX),
  `TABLE` STRING(MAX)
) PRIMARY KEY(`SELECT`);
