CREATE TABLE tinyint_table (id BIGINT PRIMARY KEY, tinyint_col TINYINT);
CREATE TABLE smallint_table (id BIGINT PRIMARY KEY, smallint_col SMALLINT);
CREATE TABLE int_table (id BIGINT PRIMARY KEY, int_col INT);
CREATE TABLE bigint_table (id BIGINT PRIMARY KEY, bigint_col BIGINT);
CREATE TABLE bit_table (id BIGINT PRIMARY KEY, bit_col BIT);
CREATE TABLE decimal_table (id BIGINT PRIMARY KEY, decimal_col DECIMAL(18, 2));
CREATE TABLE numeric_table (id BIGINT PRIMARY KEY, numeric_col NUMERIC(18, 2));
CREATE TABLE money_table (id BIGINT PRIMARY KEY, money_col MONEY);
CREATE TABLE smallmoney_table (id BIGINT PRIMARY KEY, smallmoney_col SMALLMONEY);
CREATE TABLE float_table (id BIGINT PRIMARY KEY, float_col FLOAT);
CREATE TABLE real_table (id BIGINT PRIMARY KEY, real_col REAL);
CREATE TABLE date_table (id BIGINT PRIMARY KEY, date_col DATE);
CREATE TABLE time_table (id BIGINT PRIMARY KEY, time_col TIME);
CREATE TABLE datetime2_table (id BIGINT PRIMARY KEY, datetime2_col DATETIME2);
CREATE TABLE datetimeoffset_table (id BIGINT PRIMARY KEY, datetimeoffset_col DATETIMEOFFSET);
CREATE TABLE datetime_table (id BIGINT PRIMARY KEY, datetime_col DATETIME);
CREATE TABLE smalldatetime_table (id BIGINT PRIMARY KEY, smalldatetime_col SMALLDATETIME);
CREATE TABLE char_table (id BIGINT PRIMARY KEY, char_col CHAR(10));
CREATE TABLE varchar_table (id BIGINT PRIMARY KEY, varchar_col VARCHAR(255));
CREATE TABLE text_table (id BIGINT PRIMARY KEY, text_col TEXT);
CREATE TABLE nchar_table (id BIGINT PRIMARY KEY, nchar_col NCHAR(10));
CREATE TABLE nvarchar_table (id BIGINT PRIMARY KEY, nvarchar_col NVARCHAR(255));
CREATE TABLE ntext_table (id BIGINT PRIMARY KEY, ntext_col NTEXT);
CREATE TABLE binary_table (id BIGINT PRIMARY KEY, binary_col BINARY(10));
CREATE TABLE varbinary_table (id BIGINT PRIMARY KEY, varbinary_col VARBINARY(255));
CREATE TABLE image_table (id BIGINT PRIMARY KEY, image_col IMAGE);
CREATE TABLE uniqueidentifier_table (id BIGINT PRIMARY KEY, uniqueidentifier_col UNIQUEIDENTIFIER);
CREATE TABLE xml_table (id BIGINT PRIMARY KEY, xml_col XML);
