global:
  region: "asia-south1"
  project_id: "daring-fiber-439305-v4"

bucket:
  name: "reverse-replication-bucket" 

spanner:
  name: "spanner-rr"  
  display_name: "spanner-rr"
  num_nodes: 1
  edition: "STANDARD"
  config: "regional-asia-south1"  

network:
  vpc_name: "spanner-to-cassandra" 
  auto_create_subnetworks: false
  description: "spanner to cassandra"
  subnet_name: "spanner-to-cassandra-asia-south1"
  subnet_ip: "10.0.0.0/16"
  subnet_description: "Spanner to Cassandra asia south 1"

cassandra:
  instance_name: "cassandra-rr"
  zone: "asia-south1-b"
  instance: "linux"
  instance_type: "n2-standard-2"
  disk_size_gb: 100
  disk_type: "pd-balanced"
  image: "ubuntu-os-cloud/ubuntu-2204-lts"
  create_internal_static_ip: true
  create_external_static_ip: true
  allow_stopping_for_update: true    

firewall-cassandra:
  name: "allow-cassandra-rr"
  description: "allow cassandra"
  protocol: "tcp"
  ports: ["7000", "7001", "9042", "7199"]
  source_ranges: ["10.0.0.0/8"]
  target_tags: ["cassandra"]

firewall-ssh:
  name: "allow-ssh-rr"
  description: "allow ssh"
  protocol: "tcp"
  ports: ["22"]
  source_ranges: ["0.0.0.0/0"]
  target_tags: ["cassandra"]  


