CREATE TABLE Level1 (
  Level1Id INT64 NOT NULL,
  Name STRING(100)
) PRIMARY KEY (Level1Id);

CREATE TABLE Level2 (
  Level1Id INT64 NOT NULL,
  Level2Id INT64 NOT NULL,
  Name STRING(100)
) PRIMARY KEY (Level1Id, Level2Id),
  INTERLEAVE IN PARENT Level1 ON DELETE CASCADE;

CREATE TABLE Level3 (
  Level1Id INT64 NOT NULL,
  Level2Id INT64 NOT NULL,
  Level3Id INT64 NOT NULL,
  Name STRING(100)
) PRIMARY KEY (Level1Id, Level2Id, Level3Id),
  INTERLEAVE IN PARENT Level2 ON DELETE CASCADE;

CREATE TABLE Level4 (
  Level1Id INT64 NOT NULL,
  Level2Id INT64 NOT NULL,
  Level3Id INT64 NOT NULL,
  Level4Id INT64 NOT NULL,
  Name STRING(100)
) PRIMARY KEY (Level1Id, Level2Id, Level3Id, Level4Id),
  INTERLEAVE IN PARENT Level3 ON DELETE CASCADE;

CREATE TABLE Level5 (
  Level1Id INT64 NOT NULL,
  Level2Id INT64 NOT NULL,
  Level3Id INT64 NOT NULL,
  Level4Id INT64 NOT NULL,
  Level5Id INT64 NOT NULL,
  Name STRING(100)
) PRIMARY KEY (Level1Id, Level2Id, Level3Id, Level4Id, Level5Id),
  INTERLEAVE IN PARENT Level4 ON DELETE CASCADE;

CREATE TABLE Level6 (
  Level1Id INT64 NOT NULL,
  Level2Id INT64 NOT NULL,
  Level3Id INT64 NOT NULL,
  Level4Id INT64 NOT NULL,
  Level5Id INT64 NOT NULL,
  Level6Id INT64 NOT NULL,
  Name STRING(100)
) PRIMARY KEY (Level1Id, Level2Id, Level3Id, Level4Id, Level5Id, Level6Id),
  INTERLEAVE IN PARENT Level5 ON DELETE CASCADE;

CREATE TABLE Level7 (
  Level1Id INT64 NOT NULL,
  Level2Id INT64 NOT NULL,
  Level3Id INT64 NOT NULL,
  Level4Id INT64 NOT NULL,
  Level5Id INT64 NOT NULL,
  Level6Id INT64 NOT NULL,
  Level7Id INT64 NOT NULL,
  Name STRING(100)
) PRIMARY KEY (Level1Id, Level2Id, Level3Id, Level4Id, Level5Id, Level6Id, Level7Id),
  INTERLEAVE IN PARENT Level6 ON DELETE CASCADE;
