/*
 * Copyright (C) 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.google.cloud.teleport.v2.templates.loadtesting;

import static com.google.common.truth.Truth.assertWithMessage;

import com.google.cloud.Timestamp;
import com.google.cloud.spanner.Mutation;
import com.google.cloud.teleport.metadata.SkipDirectRunnerTest;
import com.google.cloud.teleport.metadata.TemplateLoadTest;
import com.google.cloud.teleport.v2.templates.GCSSpannerDV;
import com.google.cloud.teleport.v2.templates.GCSSpannerDVTestAsserts;
import com.google.cloud.teleport.v2.templates.GCSSpannerDVTestAsserts.TableValidationStatsDto;
import com.google.cloud.teleport.v2.templates.GCSSpannerDVTestAsserts.ValidationSummaryDto;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import org.apache.beam.it.common.PipelineLauncher.LaunchInfo;
import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

/**
 * Load test for the {@link GCSSpannerDV} template validating 5,000 tables against a pre-generated
 * GCS Avro dataset.
 */
@Category({TemplateLoadTest.class, SkipDirectRunnerTest.class})
@TemplateLoadTest(GCSSpannerDV.class)
@RunWith(JUnit4.class)
public class GCSSpannerDV5KTablesLT extends GCSSpannerDVLTBase {

  // Static Avro dataset generated by running the sourcedb-to-spanner template against a MySQL
  // source. The Spanner DDL and row insertion logic below can be reused to recreate the source
  // database if these files ever need to be regenerated.
  private static final String GCS_INPUT_DIRECTORY = "gs://nokill-avro-to-spanner-dv/5k_table_test";
  private static final int NUM_TABLES = 5000;
  private static final int ROWS_PER_TABLE = 3;
  private static final Timestamp[] ROW_TIMESTAMPS = {
    Timestamp.parseTimestamp("2026-01-01T00:00:01Z"),
    Timestamp.parseTimestamp("2026-01-01T00:00:02Z"),
    Timestamp.parseTimestamp("2026-01-01T00:00:03Z")
  };
  private static final Duration JOB_TIMEOUT = Duration.ofMinutes(30);

  @Test
  public void validate5KTablesWithMatchingRecords() throws Exception {
    // 1. Create 5,000 tables in Spanner
    List<String> statements = new ArrayList<>(NUM_TABLES);
    for (int table = 0; table < NUM_TABLES; table++) {
      statements.add(
          String.format(
              "CREATE TABLE IF NOT EXISTS table_%d ("
                  + "id INT64 NOT NULL, "
                  + "data STRING(64), "
                  + "created_at TIMESTAMP"
                  + ") PRIMARY KEY (id)",
              table));
    }
    spannerResourceManager.executeDdlStatements(statements);

    // 2. Populate 3 rows per table in Spanner to match the static Avro source
    List<Mutation> mutations = new ArrayList<>(NUM_TABLES * ROWS_PER_TABLE);
    for (int table = 0; table < NUM_TABLES; table++) {
      String tableName = "table_" + table;
      for (int row = 1; row <= ROWS_PER_TABLE; row++) {
        mutations.add(
            Mutation.newInsertOrUpdateBuilder(tableName)
                .set("id")
                .to(row)
                .set("data")
                .to(String.format("table_%d_row_%d", table, row))
                .set("created_at")
                .to(ROW_TIMESTAMPS[row - 1])
                .build());
      }
    }
    spannerResourceManager.write(mutations);

    // 3. Assert Spanner schema and final table population before launching the validation job
    assertWithMessage("Total tables present in Spanner INFORMATION_SCHEMA")
        .that(
            spannerResourceManager
                .runQuery("SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = ''")
                .get(0)
                .getLong(0))
        .isEqualTo((long) NUM_TABLES);
    assertWithMessage("Row count in Spanner for table_%s", NUM_TABLES - 1)
        .that(spannerResourceManager.getRowCount("table_" + (NUM_TABLES - 1)))
        .isEqualTo((long) ROWS_PER_TABLE);

    // 4. Launch validation pipeline and wait for completion
    LaunchInfo jobInfo = launchValidationJob(GCS_INPUT_DIRECTORY, JOB_TIMEOUT);
    collectAndExportMetrics(jobInfo);

    // 5. Assert BigQuery validation results
    GCSSpannerDVTestAsserts.assertValidationSummary(
        bigQueryResourceManager,
        List.of(
            new ValidationSummaryDto(
                /* status= */ "MATCH",
                /* totalTablesValidated= */ (long) NUM_TABLES,
                /* totalRowsMatched= */ (long) NUM_TABLES * ROWS_PER_TABLE,
                /* totalRowsMismatched= */ 0L,
                /* tablesWithMismatches= */ "")));

    List<TableValidationStatsDto> expectedStats = new ArrayList<>(NUM_TABLES);
    for (int table = 0; table < NUM_TABLES; table++) {
      expectedStats.add(
          new TableValidationStatsDto(
              /* schemaName= */ null,
              /* tableName= */ "table_" + table,
              /* status= */ "MATCH",
              /* sourceRowCount= */ (long) ROWS_PER_TABLE,
              /* destinationRowCount= */ (long) ROWS_PER_TABLE,
              /* matchedRowCount= */ (long) ROWS_PER_TABLE,
              /* mismatchRowCount= */ 0L));
    }
    GCSSpannerDVTestAsserts.assertTableValidationStats(bigQueryResourceManager, expectedStats);
  }
}
