/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.beam.it.jdbc;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Comparator;
import java.util.stream.Stream;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.testcontainers.containers.Container.ExecResult;
import org.testcontainers.containers.MySQLContainer;
import org.testcontainers.utility.DockerImageName;

/**
 * Custom MySQL resource manager that enables SSL and dynamically extracts the ephemeral
 * certificates generated by the MySQL daemon at startup, converting them into JKS files that can be
 * uploaded to GCS for the Dataflow pipeline to use.
 */
public class SSLMySQLResourceManager extends AbstractJDBCResourceManager<MySQLContainer<?>> {

  private static final Logger LOG = LoggerFactory.getLogger(SSLMySQLResourceManager.class);
  private static final String DEFAULT_MYSQL_CONTAINER_NAME = "mysql";
  private static final String DEFAULT_MYSQL_CONTAINER_TAG = "8.0.30";

  private final MySQLContainer<?> container;

  private String keystorePath;
  private String truststorePath;
  private Path tempDir;

  private SSLMySQLResourceManager(MySQLContainer<?> container, Builder builder) {
    super(container, builder);
    this.container = container;
    try {
      generateAndExtractJKS();
    } catch (Exception e) {
      throw new RuntimeException("Failed to generate and extract SSL certificates", e);
    }
  }

  public static Builder builder(String testId) {
    return new Builder(testId);
  }

  @Override
  protected int getJDBCPort() {
    return MySQLContainer.MYSQL_PORT;
  }

  @Override
  public String getJDBCPrefix() {
    return "mysql";
  }

  @Override
  public void cleanupAll() {
    try {
      super.cleanupAll();
    } finally {
      if (tempDir != null && Files.exists(tempDir)) {
        try (Stream<Path> walk = Files.walk(tempDir)) {
          walk.sorted(Comparator.reverseOrder()).map(Path::toFile).forEach(File::delete);
          LOG.info("Cleaned up temporary directory: {}", tempDir);
        } catch (IOException e) {
          LOG.warn("Failed to clean up temporary directory: {}", tempDir, e);
        }
      }
    }
  }

  private void generateAndExtractJKS() throws IOException, InterruptedException {
    String password = getPassword();
    LOG.info("Generating PKCS12 keystore inside MySQL container...");
    ExecResult result =
        container.execInContainer(
            "openssl",
            "pkcs12",
            "-export",
            "-in",
            "/var/lib/mysql/client-cert.pem",
            "-inkey",
            "/var/lib/mysql/client-key.pem",
            "-out",
            "/var/lib/mysql/keystore.p12",
            "-name",
            "mysqlclient",
            "-password",
            "pass:" + password);

    if (result.getExitCode() != 0) {
      throw new RuntimeException(
          "Failed to generate pkcs12 inside container: " + result.getStderr());
    }

    this.tempDir = Files.createTempDirectory("mysql-ssl-");

    LOG.info("Copying certificates out of container to {}", tempDir);
    container.copyFileFromContainer("/var/lib/mysql/ca.pem", tempDir.resolve("ca.pem").toString());
    container.copyFileFromContainer(
        "/var/lib/mysql/keystore.p12", tempDir.resolve("keystore.p12").toString());

    String keytool = Paths.get(System.getProperty("java.home"), "bin", "keytool").toString();

    // Create Truststore JKS
    Path truststore = tempDir.resolve("truststore.jks");
    LOG.info("Generating truststore.jks");
    ProcessBuilder pbTrust =
        new ProcessBuilder(
            keytool,
            "-importcert",
            "-alias",
            "mysqlca",
            "-file",
            tempDir.resolve("ca.pem").toString(),
            "-keystore",
            truststore.toString(),
            "-storepass",
            password,
            "-noprompt");
    runProcess(pbTrust, "Failed to generate truststore.jks");

    // Convert PKCS12 to Keystore JKS
    Path keystore = tempDir.resolve("keystore.jks");
    LOG.info("Generating keystore.jks");
    ProcessBuilder pbKey =
        new ProcessBuilder(
            keytool,
            "-importkeystore",
            "-srckeystore",
            tempDir.resolve("keystore.p12").toString(),
            "-srcstoretype",
            "PKCS12",
            "-srcstorepass",
            password,
            "-destkeystore",
            keystore.toString(),
            "-deststoretype",
            "JKS",
            "-deststorepass",
            password,
            "-noprompt");
    runProcess(pbKey, "Failed to generate keystore.jks");

    this.keystorePath = keystore.toAbsolutePath().toString();
    this.truststorePath = truststore.toAbsolutePath().toString();
    LOG.info(
        "Successfully generated Keystore: {} and Truststore: {}", keystorePath, truststorePath);
  }

  private void runProcess(ProcessBuilder pb, String errorMessage)
      throws IOException, InterruptedException {
    pb.redirectErrorStream(true);
    Process process = null;
    try {
      process = pb.start();
      int exitCode = process.waitFor();
      if (exitCode != 0) {
        String output =
            new String(
                process.getInputStream().readAllBytes(), java.nio.charset.StandardCharsets.UTF_8);
        throw new RuntimeException(
            errorMessage + ". Exit code: " + exitCode + ", Output: " + output);
      }
    } finally {
      if (process != null) {
        process.destroy();
      }
    }
  }

  public String getKeystorePath() {
    return keystorePath;
  }

  public String getTruststorePath() {
    return truststorePath;
  }

  public static final class Builder extends AbstractJDBCResourceManager.Builder<MySQLContainer<?>> {

    public Builder(String testId) {
      super(testId, DEFAULT_MYSQL_CONTAINER_NAME, DEFAULT_MYSQL_CONTAINER_TAG);
    }

    @Override
    public SSLMySQLResourceManager build() {
      MySQLContainer<?> container =
          new MySQLContainer<>(
              DockerImageName.parse(this.containerImageName).withTag(this.containerImageTag));
      return new SSLMySQLResourceManager(container, this);
    }
  }
}
