CREATE TABLE AllDatatypes (
    id INT PRIMARY KEY,
    tinyint_col TINYINT,
    tinyint_bool_col TINYINT(1),
    smallint_col SMALLINT,
    mediumint_col MEDIUMINT,
    int_col INT,
    bigint_col BIGINT,
    decimal_col DECIMAL(65, 30),
    tinyint_unsigned_col TINYINT UNSIGNED,
    smallint_unsigned_col SMALLINT UNSIGNED,
    mediumint_unsigned_col MEDIUMINT UNSIGNED,
    int_unsigned_col INT UNSIGNED,
    bigint_unsigned_col BIGINT UNSIGNED,
    float_col FLOAT,
    double_col DOUBLE,
    bit_col BIT(64),
    bit_bool_col BIT(1),
    date_col DATE,
    time_col TIME(6),
    datetime_col DATETIME(6),
    timestamp_col TIMESTAMP(6) NULL DEFAULT NULL,
    year_col YEAR,
    char_col CHAR(255),
    varchar_col VARCHAR(2000),
    binary_col BINARY(255),
    varbinary_col VARBINARY(2000),
    tinyblob_col TINYBLOB,
    blob_col BLOB,
    mediumblob_col MEDIUMBLOB,
    longblob_col LONGBLOB,
    tinytext_col TINYTEXT,
    text_col TEXT,
    mediumtext_col MEDIUMTEXT,
    longtext_col LONGTEXT,
    enum_col ENUM('v1', 'v2', 'v3'),
    set_col SET('v1', 'v2', 'v3'),
    json_col JSON
);
