CREATE TABLE AllDatatypes (
    id INT PRIMARY KEY,
    tinyint_col TINYINT,
    tinyint_bool_col TINYINT(1),
    smallint_col SMALLINT,
    mediumint_col MEDIUMINT,
    int_col INT,
    bigint_col BIGINT,
    decimal_col DECIMAL(10, 2),
    numeric_col NUMERIC(10, 2),
    float_col FLOAT,
    double_col DOUBLE,
    bit_col BIT(64),
    bit_bool_col BIT(1),
    date_col DATE,
    time_col TIME,
    datetime_col DATETIME,
    timestamp_col TIMESTAMP NULL DEFAULT NULL,
    year_col YEAR,
    char_col CHAR(20),
    varchar_col VARCHAR(100),
    binary_col BINARY(20),
    varbinary_col VARBINARY(100),
    tinyblob_col TINYBLOB,
    blob_col BLOB,
    mediumblob_col MEDIUMBLOB,
    longblob_col LONGBLOB,
    tinytext_col TINYTEXT,
    text_col TEXT,
    mediumtext_col MEDIUMTEXT,
    longtext_col LONGTEXT,
    enum_col ENUM('A', 'B', 'C'),
    set_col SET('A', 'B', 'C'),
    json_col JSON,
    spatial_col GEOMETRY
);
