
CREATE TABLE IF NOT EXISTS
  MY_TABLE ( ID INT64 NOT NULL,
    VAL INT64,
    )
PRIMARY KEY
  (ID);

CREATE TABLE IF NOT EXISTS
  ALLTYPES ( BOOL_FIELD STRING(MAX) NOT NULL,
    INT64_FIELD INT64 NOT NULL,
    FLOAT64_FIELD FLOAT64 NOT NULL,
    STRING_FIELD STRING(MAX) NOT NULL,
    BYTES_FIELD BYTES(MAX) NOT NULL,
    TIMESTAMP_FIELD TIMESTAMP NOT NULL,
    DATE_FIELD DATE NOT NULL,
    NUMERIC_FIELD NUMERIC NOT NULL,
    VAL INT64,
    )
PRIMARY KEY
  (BOOL_FIELD,
    INT64_FIELD,
    FLOAT64_FIELD,
    STRING_FIELD,
    BYTES_FIELD,
    TIMESTAMP_FIELD,
    DATE_FIELD,
    NUMERIC_FIELD);
