
CREATE TABLE MY_TABLE (
    ID NUMBER NOT NULL PRIMARY KEY,
    VAL NUMBER
);
ALTER TABLE MY_TABLE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

CREATE TABLE ALLTYPES (
    BOOL_FIELD VARCHAR2(10) NOT NULL,
    INT64_FIELD NUMBER NOT NULL,
    FLOAT64_FIELD BINARY_DOUBLE NOT NULL,
    STRING_FIELD VARCHAR2(4000) NOT NULL,
    BYTES_FIELD RAW(2000) NOT NULL,
    TIMESTAMP_FIELD TIMESTAMP NOT NULL,
    DATE_FIELD DATE NOT NULL,
    NUMERIC_FIELD NUMBER NOT NULL,
    VAL NUMBER,
    PRIMARY KEY (BOOL_FIELD, INT64_FIELD, FLOAT64_FIELD, STRING_FIELD, BYTES_FIELD, TIMESTAMP_FIELD, DATE_FIELD, NUMERIC_FIELD)
);
ALTER TABLE ALLTYPES ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
