CREATE TABLE `AllDatatypeColumns` (
    `varchar_column` varchar(20) NOT NULL,
    `tinyint_column` tinyint,              
    `text_column` text,                    
    `date_column` date,                    
    `smallint_column` smallint,            
    `mediumint_column` mediumint,          
    `int_column` int,                     
    `bigint_column` bigint,                
    `float_column` float(10,2),            
    `double_column` double,                
    `decimal_column` decimal(10,2),        
    `datetime_column` datetime,           
    `timestamp_column` timestamp,          
    `time_column` time,                    
    `year_column` year,                    
    `char_column` char(10),                
    `tinyblob_column` tinyblob,            
    `tinytext_column` tinytext,            
    `blob_column` blob,                    
    `mediumblob_column` mediumblob,       
    `mediumtext_column` mediumtext,        
    `longblob_column` longblob,            
    `longtext_column` longtext,            
    `enum_column` enum('1','2','3'),       
    `bool_column` tinyint(1),              
    `other_bool_column` tinyint(1),        
    `binary_column` binary(10),            
    `varbinary_column` varbinary(20),      
    `bit_column` bit(7),                   
    PRIMARY KEY (`varchar_column`)
);