

# Autogenerated file. DO NOT EDIT.
#
# Copyright (C) 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
#


variable "on_delete" {
  type        = string
  description = "One of \"drain\" or \"cancel\". Specifies behavior of deletion during terraform destroy."
}

variable "project" {
  type        = string
  description = "The Google Cloud Project ID within which this module provisions resources."
}

variable "region" {
  type        = string
  description = "The region in which the created job should run."
}

variable "inputFilePattern" {
  type = string
  description = "This is the file location for Datastream file input in Cloud Storage. Normally, this will be gs://${BUCKET}/${ROOT_PATH}/."
}

variable "gcsPubSubSubscription" {
  type = string
  description = "The Pub/Sub subscription being used in a Cloud Storage notification policy. The name should be in the format of projects/<project-id>/subscriptions/<subscription-name>."
  default = ""
}

variable "inputFileFormat" {
  type = string
  description = "This is the format of the output file produced by Datastream. by default this will be avro."
  default = "avro"
}

variable "streamName" {
  type = string
  description = "This is the name or template for the stream to poll for schema information. Default is {_metadata_stream}. The default value is enough under most conditions."
  default = ""
}

variable "rfcStartDateTime" {
  type = string
  description = "The starting DateTime used to fetch from Cloud Storage (https://tools.ietf.org/html/rfc3339). Defaults to: 1970-01-01T00:00:00.00Z."
  default = "1970-01-01T00:00:00.00Z"
}

variable "dataStreamRootUrl" {
  type = string
  description = "Datastream API Root URL. Defaults to: https://datastream.googleapis.com/."
  default = "https://datastream.googleapis.com/"
}

variable "databaseType" {
  type = string
  description = "The database type to write to (for example, Postgres). Defaults to: postgres."
  default = "postgres"
}

variable "databaseHost" {
  type = string
  description = "Database Host to connect on."
}

variable "databasePort" {
  type = string
  description = "Database Port to connect on (default 5432)."
  default = "5432"
}

variable "databaseUser" {
  type = string
  description = "Database User to connect with."
}

variable "databasePassword" {
  type = string
  description = "Database Password for given user."
}

variable "databaseName" {
  type = string
  description = "The database name to connect to. Defaults to: postgres."
  default = "postgres"
}

variable "schemaMap" {
  type = string
  description = "A map of key/values used to dictate schema name changes (ie. old_name:new_name,CaseError:case_error). Defaults to empty."
  default = ""
}

variable "customConnectionString" {
  type = string
  description = "Optional connection string which will be used instead of the default database string."
  default = ""
}


provider "google-beta" {
    project = var.project
}

variable "additional_experiments" {
	type = set(string)
	description = "List of experiments that should be used by the job. An example value is  'enable_stackdriver_agent_metrics'."
	default = null
}

variable "autoscaling_algorithm" {
	type = string
	description = "The algorithm to use for autoscaling"
	default = null
}

variable "enable_streaming_engine" {
	type = bool
	description = "Indicates if the job should use the streaming engine feature."
	default = null
}

variable "ip_configuration" {
	type = string
	description = "The configuration for VM IPs. Options are 'WORKER_IP_PUBLIC' or 'WORKER_IP_PRIVATE'."
	default = null
}

variable "kms_key_name" {
	type = string
	description = "The name for the Cloud KMS key for the job. Key format is: projects/PROJECT_ID/locations/LOCATION/keyRings/KEY_RING/cryptoKeys/KEY"
	default = null
}

variable "labels" {
	type = map(string)
	description = "User labels to be specified for the job. Keys and values should follow the restrictions specified in the labeling restrictions page. NOTE: This field is non-authoritative, and will only manage the labels present in your configuration.				Please refer to the field 'effective_labels' for all of the labels present on the resource."
	default = null
}

variable "launcher_machine_type" {
	type = string
	description = "The machine type to use for launching the job. The default is n1-standard-1."
	default = null
}

variable "machine_type" {
	type = string
	description = "The machine type to use for the job."
	default = null
}

variable "max_workers" {
	type = number
	description = "The maximum number of Google Compute Engine instances to be made available to your pipeline during execution, from 1 to 1000."
	default = null
}

variable "name" {
	type = string
}

variable "network" {
	type = string
	description = "The network to which VMs will be assigned. If it is not provided, 'default' will be used."
	default = null
}

variable "num_workers" {
	type = number
	description = "The initial number of Google Compute Engine instances for the job."
	default = null
}

variable "sdk_container_image" {
	type = string
	description = "Docker registry location of container image to use for the 'worker harness. Default is the container for the version of the SDK. Note this field is only valid for portable pipelines."
	default = null
}

variable "service_account_email" {
	type = string
	description = "The Service Account email used to create the job."
	default = null
}

variable "skip_wait_on_job_termination" {
	type = bool
	description = "If true, treat DRAINING and CANCELLING as terminal job states and do not wait for further changes before removing from terraform state and moving on. WARNING: this will lead to job name conflicts if you do not ensure that the job names are different, e.g. by embedding a release ID or by using a random_id."
	default = null
}

variable "staging_location" {
	type = string
	description = "The Cloud Storage path to use for staging files. Must be a valid Cloud Storage URL, beginning with gs://."
	default = null
}

variable "subnetwork" {
	type = string
	description = "The subnetwork to which VMs will be assigned. Should be of the form 'regions/REGION/subnetworks/SUBNETWORK'."
	default = null
}

variable "temp_location" {
	type = string
	description = "The Cloud Storage path to use for temporary files. Must be a valid Cloud Storage URL, beginning with gs://."
	default = null
}

resource "google_dataflow_flex_template_job" "generated" {
    container_spec_gcs_path = "gs://dataflow-templates-${var.region}/latest/flex/Cloud_Datastream_to_SQL"
    parameters = {
        inputFilePattern = var.inputFilePattern
        gcsPubSubSubscription = var.gcsPubSubSubscription
        inputFileFormat = var.inputFileFormat
        streamName = var.streamName
        rfcStartDateTime = var.rfcStartDateTime
        dataStreamRootUrl = var.dataStreamRootUrl
        databaseType = var.databaseType
        databaseHost = var.databaseHost
        databasePort = var.databasePort
        databaseUser = var.databaseUser
        databasePassword = var.databasePassword
        databaseName = var.databaseName
        schemaMap = var.schemaMap
        customConnectionString = var.customConnectionString
    }
    
	additional_experiments = var.additional_experiments
	autoscaling_algorithm = var.autoscaling_algorithm
	enable_streaming_engine = var.enable_streaming_engine
	ip_configuration = var.ip_configuration
	kms_key_name = var.kms_key_name
	labels = var.labels
	launcher_machine_type = var.launcher_machine_type
	machine_type = var.machine_type
	max_workers = var.max_workers
	name = var.name
	network = var.network
	num_workers = var.num_workers
	sdk_container_image = var.sdk_container_image
	service_account_email = var.service_account_email
	skip_wait_on_job_termination = var.skip_wait_on_job_termination
	staging_location = var.staging_location
	subnetwork = var.subnetwork
	temp_location = var.temp_location
}

