CREATE TABLE tinyint_table (id INT NOT NULL PRIMARY KEY, tinyint_col TINYINT);
CREATE TABLE smallint_table (id INT NOT NULL PRIMARY KEY, smallint_col SMALLINT);
CREATE TABLE int_table (id INT NOT NULL PRIMARY KEY, int_col INT);
CREATE TABLE bigint_table (id INT NOT NULL PRIMARY KEY, bigint_col BIGINT);
CREATE TABLE bit_table (id INT NOT NULL PRIMARY KEY, bit_col BIT);
CREATE TABLE decimal_table (id INT NOT NULL PRIMARY KEY, decimal_col DECIMAL(18, 4));
CREATE TABLE numeric_table (id INT NOT NULL PRIMARY KEY, numeric_col NUMERIC(18, 4));
CREATE TABLE money_table (id INT NOT NULL PRIMARY KEY, money_col MONEY);
CREATE TABLE smallmoney_table (id INT NOT NULL PRIMARY KEY, smallmoney_col SMALLMONEY);
CREATE TABLE float_table (id INT NOT NULL PRIMARY KEY, float_col FLOAT);
CREATE TABLE real_table (id INT NOT NULL PRIMARY KEY, real_col REAL);
CREATE TABLE date_table (id INT NOT NULL PRIMARY KEY, date_col DATE);
CREATE TABLE time_table (id INT NOT NULL PRIMARY KEY, time_col TIME);
CREATE TABLE datetime_table (id INT NOT NULL PRIMARY KEY, datetime_col DATETIME);
CREATE TABLE datetime2_table (id INT NOT NULL PRIMARY KEY, datetime2_col DATETIME2);
CREATE TABLE smalldatetime_table (id INT NOT NULL PRIMARY KEY, smalldatetime_col SMALLDATETIME);
CREATE TABLE datetimeoffset_table (id INT NOT NULL PRIMARY KEY, datetimeoffset_col DATETIMEOFFSET);
CREATE TABLE char_table (id INT NOT NULL PRIMARY KEY, char_col CHAR(20));
CREATE TABLE varchar_table (id INT NOT NULL PRIMARY KEY, varchar_col VARCHAR(200));
CREATE TABLE text_table (id INT NOT NULL PRIMARY KEY, text_col TEXT);
CREATE TABLE nchar_table (id INT NOT NULL PRIMARY KEY, nchar_col NCHAR(20));
CREATE TABLE nvarchar_table (id INT NOT NULL PRIMARY KEY, nvarchar_col NVARCHAR(200));
CREATE TABLE ntext_table (id INT NOT NULL PRIMARY KEY, ntext_col NTEXT);
CREATE TABLE binary_table (id INT NOT NULL PRIMARY KEY, binary_col BINARY(5));
CREATE TABLE varbinary_table (id INT NOT NULL PRIMARY KEY, varbinary_col VARBINARY(200));
CREATE TABLE image_table (id INT NOT NULL PRIMARY KEY, image_col IMAGE);
CREATE TABLE uniqueidentifier_table (id INT NOT NULL PRIMARY KEY, uniqueidentifier_col UNIQUEIDENTIFIER);
CREATE TABLE xml_table (id INT NOT NULL PRIMARY KEY, xml_col XML);

CREATE TABLE tinyint_to_string_table (id INT NOT NULL PRIMARY KEY, tinyint_to_string_col TINYINT);
CREATE TABLE smallint_to_string_table (id INT NOT NULL PRIMARY KEY, smallint_to_string_col SMALLINT);
CREATE TABLE int_to_string_table (id INT NOT NULL PRIMARY KEY, int_to_string_col INT);
CREATE TABLE bigint_to_string_table (id INT NOT NULL PRIMARY KEY, bigint_to_string_col BIGINT);
CREATE TABLE bit_to_int64_table (id INT NOT NULL PRIMARY KEY, bit_to_int64_col BIT);
CREATE TABLE bit_to_string_table (id INT NOT NULL PRIMARY KEY, bit_to_string_col BIT);
CREATE TABLE decimal_to_float64_table (id INT NOT NULL PRIMARY KEY, decimal_to_float64_col DECIMAL(18, 4));
CREATE TABLE decimal_to_string_table (id INT NOT NULL PRIMARY KEY, decimal_to_string_col DECIMAL(18, 4));
CREATE TABLE numeric_to_float64_table (id INT NOT NULL PRIMARY KEY, numeric_to_float64_col NUMERIC(18, 4));
CREATE TABLE numeric_to_string_table (id INT NOT NULL PRIMARY KEY, numeric_to_string_col NUMERIC(18, 4));
CREATE TABLE money_to_float64_table (id INT NOT NULL PRIMARY KEY, money_to_float64_col MONEY);
CREATE TABLE money_to_string_table (id INT NOT NULL PRIMARY KEY, money_to_string_col MONEY);
CREATE TABLE smallmoney_to_float64_table (id INT NOT NULL PRIMARY KEY, smallmoney_to_float64_col SMALLMONEY);
CREATE TABLE smallmoney_to_string_table (id INT NOT NULL PRIMARY KEY, smallmoney_to_string_col SMALLMONEY);
CREATE TABLE float_to_string_table (id INT NOT NULL PRIMARY KEY, float_to_string_col FLOAT);
CREATE TABLE real_to_float64_table (id INT NOT NULL PRIMARY KEY, real_to_float64_col REAL);
CREATE TABLE real_to_string_table (id INT NOT NULL PRIMARY KEY, real_to_string_col REAL);
CREATE TABLE date_to_string_table (id INT NOT NULL PRIMARY KEY, date_to_string_col DATE);
CREATE TABLE datetime_to_string_table (id INT NOT NULL PRIMARY KEY, datetime_to_string_col DATETIME);
CREATE TABLE datetime2_to_string_table (id INT NOT NULL PRIMARY KEY, datetime2_to_string_col DATETIME2);
CREATE TABLE smalldatetime_to_string_table (id INT NOT NULL PRIMARY KEY, smalldatetime_to_string_col SMALLDATETIME);
CREATE TABLE char_to_bytes_table (id INT NOT NULL PRIMARY KEY, char_to_bytes_col CHAR(20));
CREATE TABLE varchar_to_bytes_table (id INT NOT NULL PRIMARY KEY, varchar_to_bytes_col VARCHAR(200));
CREATE TABLE nchar_to_bytes_table (id INT NOT NULL PRIMARY KEY, nchar_to_bytes_col NCHAR(20));
CREATE TABLE nvarchar_to_bytes_table (id INT NOT NULL PRIMARY KEY, nvarchar_to_bytes_col NVARCHAR(200));
CREATE TABLE binary_to_string_table (id INT NOT NULL PRIMARY KEY, binary_to_string_col BINARY(5));
CREATE TABLE varbinary_to_string_table (id INT NOT NULL PRIMARY KEY, varbinary_to_string_col VARBINARY(200));
CREATE TABLE image_to_string_table (id INT NOT NULL PRIMARY KEY, image_to_string_col IMAGE);
CREATE TABLE uniqueidentifier_to_bytes_table (id INT NOT NULL PRIMARY KEY, uniqueidentifier_to_bytes_col UNIQUEIDENTIFIER);
CREATE TABLE xml_to_bytes_table (id INT NOT NULL PRIMARY KEY, xml_to_bytes_col XML);
