CREATE TABLE MaxColumnNameTable (
    id INT64 NOT NULL,
    CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC STRING(MAX)
) PRIMARY KEY (id);
