CREATE TABLE "varchar2_table" ("id" BIGINT PRIMARY KEY, "varchar2_col" VARCHAR);
CREATE TABLE "varchar2_to_varchar_table" ("id" BIGINT PRIMARY KEY, "varchar2_col" VARCHAR);
CREATE TABLE "varchar2_to_bytea_table" ("id" BIGINT PRIMARY KEY, "varchar2_col" BYTEA);
CREATE TABLE "varchar_table" ("id" BIGINT PRIMARY KEY, "varchar_col" VARCHAR);
CREATE TABLE "varchar_to_varchar_table" ("id" BIGINT PRIMARY KEY, "varchar_col" VARCHAR);
CREATE TABLE "varchar_to_bytea_table" ("id" BIGINT PRIMARY KEY, "varchar_col" BYTEA);
CREATE TABLE "char_table" ("id" BIGINT PRIMARY KEY, "char_col" VARCHAR);
CREATE TABLE "char_to_varchar_table" ("id" BIGINT PRIMARY KEY, "char_col" VARCHAR);
CREATE TABLE "char_to_bytea_table" ("id" BIGINT PRIMARY KEY, "char_col" BYTEA);
CREATE TABLE "character_table" ("id" BIGINT PRIMARY KEY, "character_col" VARCHAR);
CREATE TABLE "character_to_varchar_table" ("id" BIGINT PRIMARY KEY, "character_col" VARCHAR);
CREATE TABLE "character_to_bytea_table" ("id" BIGINT PRIMARY KEY, "character_col" BYTEA);
CREATE TABLE "nvarchar2_table" ("id" BIGINT PRIMARY KEY, "nvarchar2_col" VARCHAR);
CREATE TABLE "nvarchar2_to_varchar_table" ("id" BIGINT PRIMARY KEY, "nvarchar2_col" VARCHAR);
CREATE TABLE "nvarchar2_to_bytea_table" ("id" BIGINT PRIMARY KEY, "nvarchar2_col" BYTEA);
CREATE TABLE "nchar_table" ("id" BIGINT PRIMARY KEY, "nchar_col" VARCHAR);
CREATE TABLE "nchar_to_varchar_table" ("id" BIGINT PRIMARY KEY, "nchar_col" VARCHAR);
CREATE TABLE "nchar_to_bytea_table" ("id" BIGINT PRIMARY KEY, "nchar_col" BYTEA);
CREATE TABLE "nchar_varying_table" ("id" BIGINT PRIMARY KEY, "nchar_varying_col" VARCHAR);
CREATE TABLE "nchar_varying_to_varchar_table" ("id" BIGINT PRIMARY KEY, "nchar_varying_col" VARCHAR);
CREATE TABLE "nchar_varying_to_bytea_table" ("id" BIGINT PRIMARY KEY, "nchar_varying_col" BYTEA);
CREATE TABLE "national_character_table" ("id" BIGINT PRIMARY KEY, "national_character_col" VARCHAR);
CREATE TABLE "national_character_to_varchar_table" ("id" BIGINT PRIMARY KEY, "national_character_col" VARCHAR);
CREATE TABLE "national_character_to_bytea_table" ("id" BIGINT PRIMARY KEY, "national_character_col" BYTEA);
CREATE TABLE "national_char_table" ("id" BIGINT PRIMARY KEY, "national_char_col" VARCHAR);
CREATE TABLE "national_char_to_varchar_table" ("id" BIGINT PRIMARY KEY, "national_char_col" VARCHAR);
CREATE TABLE "national_char_to_bytea_table" ("id" BIGINT PRIMARY KEY, "national_char_col" BYTEA);
CREATE TABLE "national_character_varying_table" ("id" BIGINT PRIMARY KEY, "national_character_varying_col" VARCHAR);
CREATE TABLE "national_character_varying_to_varchar_table" ("id" BIGINT PRIMARY KEY, "national_character_varying_col" VARCHAR);
CREATE TABLE "national_character_varying_to_bytea_table" ("id" BIGINT PRIMARY KEY, "national_character_varying_col" BYTEA);
CREATE TABLE "national_char_varying_table" ("id" BIGINT PRIMARY KEY, "national_char_varying_col" VARCHAR);
CREATE TABLE "national_char_varying_to_varchar_table" ("id" BIGINT PRIMARY KEY, "national_char_varying_col" VARCHAR);
CREATE TABLE "national_char_varying_to_bytea_table" ("id" BIGINT PRIMARY KEY, "national_char_varying_col" BYTEA);
CREATE TABLE "number_table" ("id" BIGINT PRIMARY KEY, "number_col" DOUBLE PRECISION);
CREATE TABLE "number_to_numeric_table" ("id" BIGINT PRIMARY KEY, "number_col" NUMERIC);
CREATE TABLE "number_to_varchar_table" ("id" BIGINT PRIMARY KEY, "number_col" VARCHAR);
CREATE TABLE "number_to_bigint_table" ("id" BIGINT PRIMARY KEY, "number_col" BIGINT);
CREATE TABLE "numeric_table" ("id" BIGINT PRIMARY KEY, "numeric_col" NUMERIC);
CREATE TABLE "numeric_to_double_precision_table" ("id" BIGINT PRIMARY KEY, "numeric_col" DOUBLE PRECISION);
CREATE TABLE "numeric_to_varchar_table" ("id" BIGINT PRIMARY KEY, "numeric_col" VARCHAR);
CREATE TABLE "numeric_to_bigint_table" ("id" BIGINT PRIMARY KEY, "numeric_col" BIGINT);
CREATE TABLE "decimal_table" ("id" BIGINT PRIMARY KEY, "decimal_col" NUMERIC);
CREATE TABLE "decimal_to_double_precision_table" ("id" BIGINT PRIMARY KEY, "decimal_col" DOUBLE PRECISION);
CREATE TABLE "decimal_to_varchar_table" ("id" BIGINT PRIMARY KEY, "decimal_col" VARCHAR);
CREATE TABLE "decimal_to_bigint_table" ("id" BIGINT PRIMARY KEY, "decimal_col" BIGINT);
CREATE TABLE "dec_table" ("id" BIGINT PRIMARY KEY, "dec_col" NUMERIC);
CREATE TABLE "dec_to_double_precision_table" ("id" BIGINT PRIMARY KEY, "dec_col" DOUBLE PRECISION);
CREATE TABLE "dec_to_varchar_table" ("id" BIGINT PRIMARY KEY, "dec_col" VARCHAR);
CREATE TABLE "dec_to_bigint_table" ("id" BIGINT PRIMARY KEY, "dec_col" BIGINT);
CREATE TABLE "float_table" ("id" BIGINT PRIMARY KEY, "float_col" DOUBLE PRECISION);
CREATE TABLE "float_to_numeric_table" ("id" BIGINT PRIMARY KEY, "float_col" NUMERIC);
CREATE TABLE "float_to_varchar_table" ("id" BIGINT PRIMARY KEY, "float_col" VARCHAR);
CREATE TABLE "float_to_bigint_table" ("id" BIGINT PRIMARY KEY, "float_col" BIGINT);
CREATE TABLE "double_precision_table" ("id" BIGINT PRIMARY KEY, "double_precision_col" DOUBLE PRECISION);
CREATE TABLE "double_precision_to_numeric_table" ("id" BIGINT PRIMARY KEY, "double_precision_col" NUMERIC);
CREATE TABLE "double_precision_to_varchar_table" ("id" BIGINT PRIMARY KEY, "double_precision_col" VARCHAR);
CREATE TABLE "double_precision_to_bigint_table" ("id" BIGINT PRIMARY KEY, "double_precision_col" BIGINT);
CREATE TABLE "real_table" ("id" BIGINT PRIMARY KEY, "real_col" DOUBLE PRECISION);
CREATE TABLE "real_to_numeric_table" ("id" BIGINT PRIMARY KEY, "real_col" NUMERIC);
CREATE TABLE "real_to_varchar_table" ("id" BIGINT PRIMARY KEY, "real_col" VARCHAR);
CREATE TABLE "real_to_bigint_table" ("id" BIGINT PRIMARY KEY, "real_col" BIGINT);
CREATE TABLE "binary_float_table" ("id" BIGINT PRIMARY KEY, "binary_float_col" REAL);
CREATE TABLE "binary_float_to_double_precision_table" ("id" BIGINT PRIMARY KEY, "binary_float_col" DOUBLE PRECISION);
CREATE TABLE "binary_float_to_varchar_table" ("id" BIGINT PRIMARY KEY, "binary_float_col" VARCHAR);
CREATE TABLE "binary_float_to_numeric_table" ("id" BIGINT PRIMARY KEY, "binary_float_col" NUMERIC);
CREATE TABLE "binary_double_table" ("id" BIGINT PRIMARY KEY, "binary_double_col" DOUBLE PRECISION);
CREATE TABLE "binary_double_to_varchar_table" ("id" BIGINT PRIMARY KEY, "binary_double_col" VARCHAR);
CREATE TABLE "binary_double_to_numeric_table" ("id" BIGINT PRIMARY KEY, "binary_double_col" NUMERIC);
CREATE TABLE "integer_table" ("id" BIGINT PRIMARY KEY, "integer_col" BIGINT);
CREATE TABLE "integer_to_numeric_table" ("id" BIGINT PRIMARY KEY, "integer_col" NUMERIC);
CREATE TABLE "integer_to_varchar_table" ("id" BIGINT PRIMARY KEY, "integer_col" VARCHAR);
CREATE TABLE "integer_to_double_precision_table" ("id" BIGINT PRIMARY KEY, "integer_col" DOUBLE PRECISION);
CREATE TABLE "integer_pk_table" ("integer_pk_col" BIGINT PRIMARY KEY);
CREATE TABLE "int_table" ("id" BIGINT PRIMARY KEY, "int_col" BIGINT);
CREATE TABLE "int_to_numeric_table" ("id" BIGINT PRIMARY KEY, "int_col" NUMERIC);
CREATE TABLE "int_to_varchar_table" ("id" BIGINT PRIMARY KEY, "int_col" VARCHAR);
CREATE TABLE "int_to_double_precision_table" ("id" BIGINT PRIMARY KEY, "int_col" DOUBLE PRECISION);
CREATE TABLE "int_pk_table" ("int_pk_col" BIGINT PRIMARY KEY);
CREATE TABLE "smallint_table" ("id" BIGINT PRIMARY KEY, "smallint_col" BIGINT);
CREATE TABLE "smallint_to_numeric_table" ("id" BIGINT PRIMARY KEY, "smallint_col" NUMERIC);
CREATE TABLE "smallint_to_varchar_table" ("id" BIGINT PRIMARY KEY, "smallint_col" VARCHAR);
CREATE TABLE "smallint_to_double_precision_table" ("id" BIGINT PRIMARY KEY, "smallint_col" DOUBLE PRECISION);
CREATE TABLE "smallint_pk_table" ("smallint_pk_col" BIGINT PRIMARY KEY);
CREATE TABLE "date_table" ("id" BIGINT PRIMARY KEY, "date_col" TIMESTAMPTZ);
CREATE TABLE "date_to_date_table" ("id" BIGINT PRIMARY KEY, "date_col" DATE);
CREATE TABLE "date_to_varchar_table" ("id" BIGINT PRIMARY KEY, "date_col" VARCHAR);
CREATE TABLE "date_to_bigint_table" ("id" BIGINT PRIMARY KEY, "date_col" BIGINT);
CREATE TABLE "date_pk_table" ("date_pk_col" TIMESTAMPTZ PRIMARY KEY);
CREATE TABLE "timestamp_table" ("id" BIGINT PRIMARY KEY, "timestamp_col" TIMESTAMPTZ);
CREATE TABLE "timestamp_to_varchar_table" ("id" BIGINT PRIMARY KEY, "timestamp_col" VARCHAR);
CREATE TABLE "timestamp_to_bigint_table" ("id" BIGINT PRIMARY KEY, "timestamp_col" BIGINT);
CREATE TABLE "timestamp_pk_table" ("timestamp_pk_col" TIMESTAMPTZ PRIMARY KEY);
CREATE TABLE "interval_year_to_month_table" ("id" BIGINT PRIMARY KEY, "interval_year_to_month_col" VARCHAR);
CREATE TABLE "interval_day_to_second_table" ("id" BIGINT PRIMARY KEY, "interval_day_to_second_col" VARCHAR);
CREATE TABLE "raw_table" ("id" BIGINT PRIMARY KEY, "raw_col" BYTEA);
CREATE TABLE "raw_to_bytea_table" ("id" BIGINT PRIMARY KEY, "raw_col" BYTEA);
CREATE TABLE "raw_to_varchar_base64_table" ("id" BIGINT PRIMARY KEY, "raw_col" VARCHAR);
CREATE TABLE "long_raw_table" ("id" BIGINT PRIMARY KEY, "long_raw_col" BYTEA);
CREATE TABLE "long_raw_to_varchar_base64_table" ("id" BIGINT PRIMARY KEY, "long_raw_col" VARCHAR);
CREATE TABLE "blob_table" ("id" BIGINT PRIMARY KEY, "blob_col" BYTEA);
CREATE TABLE "blob_to_varchar_base64_table" ("id" BIGINT PRIMARY KEY, "blob_col" VARCHAR);
CREATE TABLE "clob_table" ("id" BIGINT PRIMARY KEY, "clob_col" VARCHAR);
CREATE TABLE "clob_to_bytea_table" ("id" BIGINT PRIMARY KEY, "clob_col" BYTEA);
CREATE TABLE "nclob_table" ("id" BIGINT PRIMARY KEY, "nclob_col" VARCHAR);
CREATE TABLE "nclob_to_bytea_table" ("id" BIGINT PRIMARY KEY, "nclob_col" BYTEA);
CREATE TABLE "bfile_table" ("id" BIGINT PRIMARY KEY, "bfile_col" VARCHAR);
CREATE TABLE "bfile_to_bytea_table" ("id" BIGINT PRIMARY KEY, "bfile_col" BYTEA);
CREATE TABLE "bfile_to_varchar_url_table" ("id" BIGINT PRIMARY KEY, "bfile_col" VARCHAR);
CREATE TABLE "long_table" ("id" BIGINT PRIMARY KEY, "long_col" VARCHAR);
CREATE TABLE "long_to_bytea_table" ("id" BIGINT PRIMARY KEY, "long_col" BYTEA);
CREATE TABLE "rowid_table" ("id" BIGINT PRIMARY KEY, "rowid_col" VARCHAR);
CREATE TABLE "rowid_to_bytea_table" ("id" BIGINT PRIMARY KEY, "rowid_col" BYTEA);
CREATE TABLE "rowid_to_bigint_table" ("id" BIGINT PRIMARY KEY, "rowid_col" BIGINT);
CREATE TABLE "urowid_table" ("id" BIGINT PRIMARY KEY, "urowid_col" VARCHAR);
CREATE TABLE "urowid_to_bytea_table" ("id" BIGINT PRIMARY KEY, "urowid_col" BYTEA);
CREATE TABLE "urowid_to_bigint_table" ("id" BIGINT PRIMARY KEY, "urowid_col" BIGINT);
CREATE TABLE "boolean_table" ("id" BIGINT PRIMARY KEY, "boolean_col" BOOLEAN);
CREATE TABLE "boolean_to_bigint_0_1_table" ("id" BIGINT PRIMARY KEY, "boolean_col" BIGINT);
CREATE TABLE "boolean_to_varchar_true_false_table" ("id" BIGINT PRIMARY KEY, "boolean_col" VARCHAR);
CREATE TABLE "json_table" ("id" BIGINT PRIMARY KEY, "json_col" JSONB);
CREATE TABLE "json_to_varchar_table" ("id" BIGINT PRIMARY KEY, "json_col" VARCHAR);
CREATE TABLE "json_to_bytea_table" ("id" BIGINT PRIMARY KEY, "json_col" BYTEA);
CREATE TABLE "xmltype_table" ("id" BIGINT PRIMARY KEY, "xmltype_col" VARCHAR);
CREATE TABLE "xmltype_to_bytea_table" ("id" BIGINT PRIMARY KEY, "xmltype_col" BYTEA);
CREATE TABLE "sdo_geometry_table" ("id" BIGINT PRIMARY KEY, "sdo_geometry_col" VARCHAR);
CREATE TABLE "sdo_geometry_to_bytea_table" ("id" BIGINT PRIMARY KEY, "sdo_geometry_col" BYTEA);
CREATE TABLE "sdo_geometry_to_jsonb_table" ("id" BIGINT PRIMARY KEY, "sdo_geometry_col" JSONB);
CREATE TABLE "sdo_topo_geometry_table" ("id" BIGINT PRIMARY KEY, "sdo_topo_geometry_col" VARCHAR);
CREATE TABLE "sdo_topo_geometry_to_bytea_table" ("id" BIGINT PRIMARY KEY, "sdo_topo_geometry_col" BYTEA);
CREATE TABLE "sdo_topo_geometry_to_jsonb_table" ("id" BIGINT PRIMARY KEY, "sdo_topo_geometry_col" JSONB);
CREATE TABLE "sdo_georaster_table" ("id" BIGINT PRIMARY KEY, "sdo_georaster_col" BYTEA);
CREATE TABLE "sdo_georaster_to_varchar_uri_table" ("id" BIGINT PRIMARY KEY, "sdo_georaster_col" VARCHAR);
CREATE TABLE "vector_table" ("id" BIGINT PRIMARY KEY, "vector_col" double precision[]);
CREATE TABLE "vector_to_array_double_precision_table" ("id" BIGINT PRIMARY KEY, "vector_col" double precision[]);
CREATE TABLE "vector_to_bytea_table" ("id" BIGINT PRIMARY KEY, "vector_col" BYTEA);
CREATE TABLE "anydata_table" ("id" BIGINT PRIMARY KEY, "anydata_col" BYTEA);
CREATE TABLE "anydata_to_varchar_table" ("id" BIGINT PRIMARY KEY, "anydata_col" VARCHAR);
CREATE TABLE "anytype_table" ("id" BIGINT PRIMARY KEY, "anytype_col" BYTEA);
CREATE TABLE "anytype_to_varchar_table" ("id" BIGINT PRIMARY KEY, "anytype_col" VARCHAR);
CREATE TABLE "anydataset_table" ("id" BIGINT PRIMARY KEY, "anydataset_col" BYTEA);
CREATE TABLE "anydataset_to_varchar_table" ("id" BIGINT PRIMARY KEY, "anydataset_col" VARCHAR);
CREATE TABLE "uritype_table" ("id" BIGINT PRIMARY KEY, "uritype_col" VARCHAR);
CREATE TABLE "uritype_to_bytea_table" ("id" BIGINT PRIMARY KEY, "uritype_col" BYTEA);
CREATE TABLE "dburitype_table" ("id" BIGINT PRIMARY KEY, "dburitype_col" VARCHAR);
CREATE TABLE "dburitype_to_bytea_table" ("id" BIGINT PRIMARY KEY, "dburitype_col" BYTEA);
CREATE TABLE "xdburitype_table" ("id" BIGINT PRIMARY KEY, "xdburitype_col" VARCHAR);
CREATE TABLE "xdburitype_to_bytea_table" ("id" BIGINT PRIMARY KEY, "xdburitype_col" BYTEA);
CREATE TABLE "httpuritype_table" ("id" BIGINT PRIMARY KEY, "httpuritype_col" VARCHAR);
CREATE TABLE "httpuritype_to_bytea_table" ("id" BIGINT PRIMARY KEY, "httpuritype_col" BYTEA);
CREATE TABLE "expression_table" ("id" BIGINT PRIMARY KEY, "expression_col" VARCHAR);
CREATE TABLE "expression_to_bytea_table" ("id" BIGINT PRIMARY KEY, "expression_col" BYTEA);
CREATE TABLE "ordaudio_table" ("id" BIGINT PRIMARY KEY, "ordaudio_col" BYTEA);
CREATE TABLE "ordaudio_to_varchar_uri_table" ("id" BIGINT PRIMARY KEY, "ordaudio_col" VARCHAR);
CREATE TABLE "ordimage_table" ("id" BIGINT PRIMARY KEY, "ordimage_col" BYTEA);
CREATE TABLE "ordimage_to_varchar_uri_table" ("id" BIGINT PRIMARY KEY, "ordimage_col" VARCHAR);
CREATE TABLE "ordvideo_table" ("id" BIGINT PRIMARY KEY, "ordvideo_col" BYTEA);
CREATE TABLE "ordvideo_to_varchar_uri_table" ("id" BIGINT PRIMARY KEY, "ordvideo_col" VARCHAR);
CREATE TABLE "orddoc_table" ("id" BIGINT PRIMARY KEY, "orddoc_col" BYTEA);
CREATE TABLE "orddoc_to_varchar_uri_table" ("id" BIGINT PRIMARY KEY, "orddoc_col" VARCHAR);
CREATE TABLE "si_stillimage_table" ("id" BIGINT PRIMARY KEY, "si_stillimage_col" BYTEA);
CREATE TABLE "si_stillimage_to_varchar_jsonb_table" ("id" BIGINT PRIMARY KEY, "si_stillimage_col" VARCHAR);
CREATE TABLE "si_color_table" ("id" BIGINT PRIMARY KEY, "si_color_col" BYTEA);
CREATE TABLE "si_color_to_varchar_table" ("id" BIGINT PRIMARY KEY, "si_color_col" VARCHAR);
CREATE TABLE "si_averagecolor_table" ("id" BIGINT PRIMARY KEY, "si_averagecolor_col" BYTEA);
CREATE TABLE "si_averagecolor_to_varchar_table" ("id" BIGINT PRIMARY KEY, "si_averagecolor_col" VARCHAR);
CREATE TABLE "si_colorhistogram_table" ("id" BIGINT PRIMARY KEY, "si_colorhistogram_col" BYTEA);
CREATE TABLE "si_colorhistogram_to_varchar_table" ("id" BIGINT PRIMARY KEY, "si_colorhistogram_col" VARCHAR);
CREATE TABLE "si_positionalcolor_table" ("id" BIGINT PRIMARY KEY, "si_positionalcolor_col" BYTEA);
CREATE TABLE "si_positionalcolor_to_varchar_table" ("id" BIGINT PRIMARY KEY, "si_positionalcolor_col" VARCHAR);
CREATE TABLE "si_texture_table" ("id" BIGINT PRIMARY KEY, "si_texture_col" BYTEA);
CREATE TABLE "si_texture_to_varchar_table" ("id" BIGINT PRIMARY KEY, "si_texture_col" VARCHAR);
CREATE TABLE "si_featurelist_table" ("id" BIGINT PRIMARY KEY, "si_featurelist_col" BYTEA);
CREATE TABLE "si_featurelist_to_varchar_table" ("id" BIGINT PRIMARY KEY, "si_featurelist_col" VARCHAR);
CREATE TABLE "mlslabel_table" ("id" BIGINT PRIMARY KEY, "mlslabel_col" VARCHAR);
CREATE TABLE "mlslabel_to_bytea_table" ("id" BIGINT PRIMARY KEY, "mlslabel_col" BYTEA);
CREATE TABLE "ref_table" ("id" BIGINT PRIMARY KEY, "ref_col" VARCHAR);
CREATE TABLE "ref_to_bytea_table" ("id" BIGINT PRIMARY KEY, "ref_col" BYTEA);
CREATE TABLE "ref_cursor_table" ("id" BIGINT PRIMARY KEY, "ref_cursor_col" VARCHAR);
CREATE TABLE "ref_cursor_to_unsupported_table" ("id" BIGINT PRIMARY KEY, "ref_cursor_col" VARCHAR);
CREATE TABLE "varray_table" ("id" BIGINT PRIMARY KEY, "varray_col" VARCHAR[]);
CREATE TABLE "varray_to_jsonb_table" ("id" BIGINT PRIMARY KEY, "varray_col" JSONB);
CREATE TABLE "nested_table_table" ("id" BIGINT PRIMARY KEY, "nested_table_col" JSONB);
CREATE TABLE "nested_table_to_varchar_table" ("id" BIGINT PRIMARY KEY, "nested_table_col" VARCHAR);
CREATE TABLE "associative_array_table" ("id" BIGINT PRIMARY KEY, "associative_array_col" JSONB);
CREATE TABLE "associative_array_to_varchar_table" ("id" BIGINT PRIMARY KEY, "associative_array_col" VARCHAR);
CREATE TABLE "object_type_table" ("id" BIGINT PRIMARY KEY, "object_type_col" JSONB);
CREATE TABLE "object_type_to_varchar_table" ("id" BIGINT PRIMARY KEY, "object_type_col" VARCHAR);
CREATE TABLE "timestamp_with_time_zone_table" ("id" BIGINT PRIMARY KEY, "timestamp_with_time_zone_col" TIMESTAMPTZ);
CREATE TABLE "timestamp_with_time_zone_to_varchar_table" ("id" BIGINT PRIMARY KEY, "timestamp_with_time_zone_to_varchar_col" VARCHAR);
CREATE TABLE "timestamp_with_time_zone_to_bigint_table" ("id" BIGINT PRIMARY KEY, "timestamp_with_time_zone_to_bigint_col" BIGINT);
CREATE TABLE "timestamp_with_local_time_zone_table" ("id" BIGINT PRIMARY KEY, "timestamp_with_local_time_zone_col" TIMESTAMPTZ);
CREATE TABLE "timestamp_with_local_time_zone_to_varchar_table" ("id" BIGINT PRIMARY KEY, "timestamp_with_local_time_zone_to_varchar_col" VARCHAR);
CREATE TABLE "timestamp_with_local_time_zone_to_bigint_table" ("id" BIGINT PRIMARY KEY, "timestamp_with_local_time_zone_to_bigint_col" BIGINT);
