{
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "id": "cloudbilling:v1",
  "name": "cloudbilling",
  "canonicalName": "Cloudbilling",
  "version": "v1",
  "revision": "0",
  "title": "Cloud Billing API",
  "description": "Allows developers to manage billing for their Google Cloud Platform projects programmatically.",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": "https://cloud.google.com/billing/",
  "protocol": "rest",
  "rootUrl": "https://cloudbilling.googleapis.com/",
  "mtlsRootUrl": "https://cloudbilling.mtls.googleapis.com/",
  "servicePath": "",
  "baseUrl": "https://cloudbilling.googleapis.com/",
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-billing": {
          "description": "View and manage your Google Cloud Platform billing accounts"
        },
        "https://www.googleapis.com/auth/cloud-billing.readonly": {
          "description": "View your Google Cloud Platform billing accounts"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "View and manage your data across Google Cloud Platform services"
        }
      }
    }
  },
  "resources": {
    "billingAccounts": {
      "methods": {
        "get": {
          "id": "cloudbilling.billingAccounts.get",
          "path": "v1/{+name}",
          "flatPath": "v1/billingAccounts/{billingAccountsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-billing.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Gets information about a billing account. The current authenticated user must be a [viewer of the billing account](https:\/\/cloud.google.com\/billing\/docs\/how-to\/billing-access)."
        },
        "list": {
          "id": "cloudbilling.billingAccounts.list",
          "path": "v1/billingAccounts",
          "flatPath": "v1/billingAccounts",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-billing.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Lists the billing accounts that the current authenticated user has permission to [view](https:\/\/cloud.google.com\/billing\/docs\/how-to\/billing-access)."
        },
        "patch": {
          "id": "cloudbilling.billingAccounts.patch",
          "path": "v1/{+name}",
          "flatPath": "v1/billingAccounts/{billingAccountsId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Updates a billing account's fields. Currently the only field that can be edited is `display_name`. The current authenticated user must have the `billing.accounts.update` IAM permission, which is typically given to the [administrator](https:\/\/cloud.google.com\/billing\/docs\/how-to\/billing-access) of the billing account."
        },
        "create": {
          "id": "cloudbilling.billingAccounts.create",
          "path": "v1/billingAccounts",
          "flatPath": "v1/billingAccounts",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Creates a billing account. This method can only be used to create [billing subaccounts](https:\/\/cloud.google.com\/billing\/docs\/concepts) by Google Cloud resellers. When creating a subaccount, the current authenticated user must have the `billing.accounts.update` IAM permission on the master account, which is typically given to billing account [administrators](https:\/\/cloud.google.com\/billing\/docs\/how-to\/billing-access). This method will return an error if the [...]"
        },
        "getIamPolicy": {
          "id": "cloudbilling.billingAccounts.getIamPolicy",
          "path": "v1/{+resource}:getIamPolicy",
          "flatPath": "v1/billingAccounts/{billingAccountsId}:getIamPolicy",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-billing.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Gets the access control policy for a billing account. The caller must have the `billing.accounts.getIamPolicy` permission on the account, which is often given to billing account [viewers](https:\/\/cloud.google.com\/billing\/docs\/how-to\/billing-access)."
        },
        "setIamPolicy": {
          "id": "cloudbilling.billingAccounts.setIamPolicy",
          "path": "v1/{+resource}:setIamPolicy",
          "flatPath": "v1/billingAccounts/{billingAccountsId}:setIamPolicy",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Sets the access control policy for a billing account. Replaces any existing policy. The caller must have the `billing.accounts.setIamPolicy` permission on the account, which is often given to billing account [administrators](https:\/\/cloud.google.com\/billing\/docs\/how-to\/billing-access)."
        },
        "testIamPermissions": {
          "id": "cloudbilling.billingAccounts.testIamPermissions",
          "path": "v1/{+resource}:testIamPermissions",
          "flatPath": "v1/billingAccounts/{billingAccountsId}:testIamPermissions",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-billing.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Tests the access control policy for a billing account. This method takes the resource and a set of permissions as input and returns the subset of the input permissions that the caller is allowed for that resource."
        }
      }
      ,
      "resources": {
        "projects": {
          "methods": {
            "list": {
              "id": "cloudbilling.billingAccounts.projects.list",
              "path": "v1/{+name}/projects",
              "flatPath": "v1/billingAccounts/{billingAccountsId}/projects",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-billing",
                "https://www.googleapis.com/auth/cloud-billing.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Lists the projects associated with a billing account. The current authenticated user must have the `billing.resourceAssociations.list` IAM permission, which is often given to billing account [viewers](https:\/\/cloud.google.com\/billing\/docs\/how-to\/billing-access)."
            }
          }
        }
      }
    },
    "projects": {
      "methods": {
        "getBillingInfo": {
          "id": "cloudbilling.projects.getBillingInfo",
          "path": "v1/{+name}/billingInfo",
          "flatPath": "v1/projects/{projectsId}/billingInfo",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-billing.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Gets the billing information for a project. The current authenticated user must have [permission to view the project](https:\/\/cloud.google.com\/docs\/permissions-overview#h.bgs0oxofvnoo )."
        },
        "updateBillingInfo": {
          "id": "cloudbilling.projects.updateBillingInfo",
          "path": "v1/{+name}/billingInfo",
          "flatPath": "v1/projects/{projectsId}/billingInfo",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Sets or updates the billing account associated with a project. You specify the new billing account by setting the `billing_account_name` in the `ProjectBillingInfo` resource to the resource name of a billing account. Associating a project with an open billing account enables billing on the project and allows charges for resource usage. If the project already had a billing account, this method changes the billing account used for resource usage charges. *Note:* Incurred [...]"
        }
      }
    },
    "services": {
      "methods": {
        "list": {
          "id": "cloudbilling.services.list",
          "path": "v1/services",
          "flatPath": "v1/services",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-billing.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Lists all public cloud services."
        }
      }
      ,
      "resources": {
        "skus": {
          "methods": {
            "list": {
              "id": "cloudbilling.services.skus.list",
              "path": "v1/{+parent}/skus",
              "flatPath": "v1/services/{servicesId}/skus",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-billing",
                "https://www.googleapis.com/auth/cloud-billing.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Lists all publicly available SKUs for a given cloud service."
            }
          }
        }
      }
    }
  },
  "basePath": ""
}