CREATE TABLE test_key_size (
id INT AUTO_INCREMENT PRIMARY KEY,
col1 VARCHAR(150) NOT NULL,
col2 VARCHAR(150) NOT NULL,
col3 VARCHAR(150) NOT NULL,
col4 VARCHAR(150) NOT NULL,
col5 VARCHAR(150) NOT NULL,
UNIQUE KEY idx_large (col1, col2, col3, col4,col5)
)